// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/gitingress/v1/gitingress.proto (package helixgitpx.gitingress.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message helixgitpx.gitingress.v1.Push
 */
export class Push extends Message<Push> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * @generated from field: string ref = 3;
   */
  ref = "";

  /**
   * @generated from field: string old_sha = 4;
   */
  oldSha = "";

  /**
   * @generated from field: string new_sha = 5;
   */
  newSha = "";

  /**
   * @generated from field: string actor_id = 6;
   */
  actorId = "";

  /**
   * @generated from field: int32 size_bytes = 7;
   */
  sizeBytes = 0;

  /**
   * @generated from field: google.protobuf.Timestamp at = 8;
   */
  at?: Timestamp;

  constructor(data?: PartialMessage<Push>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.gitingress.v1.Push";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "old_sha", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "new_sha", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "size_bytes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Push {
    return new Push().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Push {
    return new Push().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Push {
    return new Push().fromJsonString(jsonString, options);
  }

  static equals(a: Push | PlainMessage<Push> | undefined, b: Push | PlainMessage<Push> | undefined): boolean {
    return proto3.util.equals(Push, a, b);
  }
}

/**
 * @generated from message helixgitpx.gitingress.v1.ListRecentPushesRequest
 */
export class ListRecentPushesRequest extends Message<ListRecentPushesRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<ListRecentPushesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.gitingress.v1.ListRecentPushesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRecentPushesRequest {
    return new ListRecentPushesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRecentPushesRequest {
    return new ListRecentPushesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRecentPushesRequest {
    return new ListRecentPushesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRecentPushesRequest | PlainMessage<ListRecentPushesRequest> | undefined, b: ListRecentPushesRequest | PlainMessage<ListRecentPushesRequest> | undefined): boolean {
    return proto3.util.equals(ListRecentPushesRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.gitingress.v1.ListRecentPushesResponse
 */
export class ListRecentPushesResponse extends Message<ListRecentPushesResponse> {
  /**
   * @generated from field: repeated helixgitpx.gitingress.v1.Push pushes = 1;
   */
  pushes: Push[] = [];

  constructor(data?: PartialMessage<ListRecentPushesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.gitingress.v1.ListRecentPushesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pushes", kind: "message", T: Push, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRecentPushesResponse {
    return new ListRecentPushesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRecentPushesResponse {
    return new ListRecentPushesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRecentPushesResponse {
    return new ListRecentPushesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListRecentPushesResponse | PlainMessage<ListRecentPushesResponse> | undefined, b: ListRecentPushesResponse | PlainMessage<ListRecentPushesResponse> | undefined): boolean {
    return proto3.util.equals(ListRecentPushesResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.gitingress.v1.GetRepoStatsRequest
 */
export class GetRepoStatsRequest extends Message<GetRepoStatsRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  constructor(data?: PartialMessage<GetRepoStatsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.gitingress.v1.GetRepoStatsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRepoStatsRequest {
    return new GetRepoStatsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRepoStatsRequest {
    return new GetRepoStatsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRepoStatsRequest {
    return new GetRepoStatsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRepoStatsRequest | PlainMessage<GetRepoStatsRequest> | undefined, b: GetRepoStatsRequest | PlainMessage<GetRepoStatsRequest> | undefined): boolean {
    return proto3.util.equals(GetRepoStatsRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.gitingress.v1.RepoStats
 */
export class RepoStats extends Message<RepoStats> {
  /**
   * @generated from field: int64 size_bytes = 1;
   */
  sizeBytes = protoInt64.zero;

  /**
   * @generated from field: int32 ref_count = 2;
   */
  refCount = 0;

  /**
   * @generated from field: int64 last_push_unix = 3;
   */
  lastPushUnix = protoInt64.zero;

  constructor(data?: PartialMessage<RepoStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.gitingress.v1.RepoStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "size_bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "ref_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "last_push_unix", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RepoStats {
    return new RepoStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RepoStats {
    return new RepoStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RepoStats {
    return new RepoStats().fromJsonString(jsonString, options);
  }

  static equals(a: RepoStats | PlainMessage<RepoStats> | undefined, b: RepoStats | PlainMessage<RepoStats> | undefined): boolean {
    return proto3.util.equals(RepoStats, a, b);
  }
}

/**
 * @generated from message helixgitpx.gitingress.v1.QuotaStatusRequest
 */
export class QuotaStatusRequest extends Message<QuotaStatusRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  constructor(data?: PartialMessage<QuotaStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.gitingress.v1.QuotaStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QuotaStatusRequest {
    return new QuotaStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QuotaStatusRequest {
    return new QuotaStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QuotaStatusRequest {
    return new QuotaStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QuotaStatusRequest | PlainMessage<QuotaStatusRequest> | undefined, b: QuotaStatusRequest | PlainMessage<QuotaStatusRequest> | undefined): boolean {
    return proto3.util.equals(QuotaStatusRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.gitingress.v1.QuotaStatus
 */
export class QuotaStatus extends Message<QuotaStatus> {
  /**
   * @generated from field: int64 storage_bytes_used = 1;
   */
  storageBytesUsed = protoInt64.zero;

  /**
   * @generated from field: int64 storage_bytes_limit = 2;
   */
  storageBytesLimit = protoInt64.zero;

  /**
   * @generated from field: int32 pushes_this_minute = 3;
   */
  pushesThisMinute = 0;

  /**
   * @generated from field: int32 pushes_per_minute_limit = 4;
   */
  pushesPerMinuteLimit = 0;

  constructor(data?: PartialMessage<QuotaStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.gitingress.v1.QuotaStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "storage_bytes_used", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "storage_bytes_limit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "pushes_this_minute", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "pushes_per_minute_limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QuotaStatus {
    return new QuotaStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QuotaStatus {
    return new QuotaStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QuotaStatus {
    return new QuotaStatus().fromJsonString(jsonString, options);
  }

  static equals(a: QuotaStatus | PlainMessage<QuotaStatus> | undefined, b: QuotaStatus | PlainMessage<QuotaStatus> | undefined): boolean {
    return proto3.util.equals(QuotaStatus, a, b);
  }
}

