// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/gitingress/v1/gitingress.proto (package helixgitpx.gitingress.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRepoStatsRequest, ListRecentPushesRequest, ListRecentPushesResponse, QuotaStatus, QuotaStatusRequest, RepoStats } from "./gitingress_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * GitIngressService accepts git smart-HTTP operations. The HTTP side is the
 * primary surface; this RPC is for internal operations and status.
 *
 * @generated from service helixgitpx.gitingress.v1.GitIngressService
 */
export const GitIngressService = {
  typeName: "helixgitpx.gitingress.v1.GitIngressService",
  methods: {
    /**
     * @generated from rpc helixgitpx.gitingress.v1.GitIngressService.ListRecentPushes
     */
    listRecentPushes: {
      name: "ListRecentPushes",
      I: ListRecentPushesRequest,
      O: ListRecentPushesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.gitingress.v1.GitIngressService.GetRepoStats
     */
    getRepoStats: {
      name: "GetRepoStats",
      I: GetRepoStatsRequest,
      O: RepoStats,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.gitingress.v1.GitIngressService.GetQuotaStatus
     */
    getQuotaStatus: {
      name: "GetQuotaStatus",
      I: QuotaStatusRequest,
      O: QuotaStatus,
      kind: MethodKind.Unary,
    },
  }
} as const;

