apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-app-and-env
      match:
        any:
          - resources: { kinds: [Deployment, StatefulSet, DaemonSet] }
      validate:
        message: "Workloads must declare app.kubernetes.io/name and helixgitpx.dev/env labels."
        pattern:
          metadata:
            labels:
              app.kubernetes.io/name: "?*"
              helixgitpx.dev/env: "?*"
