// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/search/v1/search.proto (package helixgitpx.search.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.search.v1.SearchMode
 */
export enum SearchMode {
  /**
   * @generated from enum value: SEARCH_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * RRF fusion: keyword + vector + code
   *
   * @generated from enum value: SEARCH_MODE_HYBRID = 1;
   */
  HYBRID = 1,

  /**
   * @generated from enum value: SEARCH_MODE_KEYWORD = 2;
   */
  KEYWORD = 2,

  /**
   * @generated from enum value: SEARCH_MODE_VECTOR = 3;
   */
  VECTOR = 3,

  /**
   * @generated from enum value: SEARCH_MODE_CODE = 4;
   */
  CODE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(SearchMode)
proto3.util.setEnumType(SearchMode, "helixgitpx.search.v1.SearchMode", [
  { no: 0, name: "SEARCH_MODE_UNSPECIFIED" },
  { no: 1, name: "SEARCH_MODE_HYBRID" },
  { no: 2, name: "SEARCH_MODE_KEYWORD" },
  { no: 3, name: "SEARCH_MODE_VECTOR" },
  { no: 4, name: "SEARCH_MODE_CODE" },
]);

/**
 * @generated from message helixgitpx.search.v1.SearchRequest
 */
export class SearchRequest extends Message<SearchRequest> {
  /**
   * @generated from field: string query = 1;
   */
  query = "";

  /**
   * @generated from field: string org_id = 2;
   */
  orgId = "";

  /**
   * @generated from field: repeated string repo_ids = 3;
   */
  repoIds: string[] = [];

  /**
   * @generated from field: helixgitpx.search.v1.SearchMode mode = 4;
   */
  mode = SearchMode.UNSPECIFIED;

  /**
   * @generated from field: int32 limit = 5;
   */
  limit = 0;

  /**
   * @generated from field: int32 offset = 6;
   */
  offset = 0;

  constructor(data?: PartialMessage<SearchRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.SearchRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "repo_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "mode", kind: "enum", T: proto3.getEnumType(SearchMode) },
    { no: 5, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchRequest {
    return new SearchRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchRequest {
    return new SearchRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchRequest {
    return new SearchRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SearchRequest | PlainMessage<SearchRequest> | undefined, b: SearchRequest | PlainMessage<SearchRequest> | undefined): boolean {
    return proto3.util.equals(SearchRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.search.v1.SearchResponse
 */
export class SearchResponse extends Message<SearchResponse> {
  /**
   * @generated from field: repeated helixgitpx.search.v1.SearchHit hits = 1;
   */
  hits: SearchHit[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  /**
   * @generated from field: int64 elapsed_ms = 3;
   */
  elapsedMs = protoInt64.zero;

  /**
   * @generated from field: helixgitpx.search.v1.SearchMode actual_mode = 4;
   */
  actualMode = SearchMode.UNSPECIFIED;

  constructor(data?: PartialMessage<SearchResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.SearchResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "hits", kind: "message", T: SearchHit, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "elapsed_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "actual_mode", kind: "enum", T: proto3.getEnumType(SearchMode) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchResponse {
    return new SearchResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchResponse {
    return new SearchResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchResponse {
    return new SearchResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SearchResponse | PlainMessage<SearchResponse> | undefined, b: SearchResponse | PlainMessage<SearchResponse> | undefined): boolean {
    return proto3.util.equals(SearchResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.search.v1.SearchHit
 */
export class SearchHit extends Message<SearchHit> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * "repo" | "pr" | "issue" | "comment" | "file"
   *
   * @generated from field: string kind = 2;
   */
  kind = "";

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * @generated from field: string snippet = 4;
   */
  snippet = "";

  /**
   * @generated from field: string url = 5;
   */
  url = "";

  /**
   * @generated from field: double score = 6;
   */
  score = 0;

  /**
   * @generated from field: double keyword_score = 7;
   */
  keywordScore = 0;

  /**
   * @generated from field: double vector_score = 8;
   */
  vectorScore = 0;

  /**
   * @generated from field: double code_score = 9;
   */
  codeScore = 0;

  constructor(data?: PartialMessage<SearchHit>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.SearchHit";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "snippet", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "keyword_score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "vector_score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 9, name: "code_score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchHit {
    return new SearchHit().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchHit {
    return new SearchHit().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchHit {
    return new SearchHit().fromJsonString(jsonString, options);
  }

  static equals(a: SearchHit | PlainMessage<SearchHit> | undefined, b: SearchHit | PlainMessage<SearchHit> | undefined): boolean {
    return proto3.util.equals(SearchHit, a, b);
  }
}

/**
 * @generated from message helixgitpx.search.v1.CodeSearchRequest
 */
export class CodeSearchRequest extends Message<CodeSearchRequest> {
  /**
   * Zoekt regex syntax
   *
   * @generated from field: string query = 1;
   */
  query = "";

  /**
   * @generated from field: string org_id = 2;
   */
  orgId = "";

  /**
   * @generated from field: repeated string repo_ids = 3;
   */
  repoIds: string[] = [];

  /**
   * @generated from field: int32 limit = 4;
   */
  limit = 0;

  constructor(data?: PartialMessage<CodeSearchRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.CodeSearchRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "repo_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CodeSearchRequest {
    return new CodeSearchRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CodeSearchRequest {
    return new CodeSearchRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CodeSearchRequest {
    return new CodeSearchRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CodeSearchRequest | PlainMessage<CodeSearchRequest> | undefined, b: CodeSearchRequest | PlainMessage<CodeSearchRequest> | undefined): boolean {
    return proto3.util.equals(CodeSearchRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.search.v1.CodeSearchResponse
 */
export class CodeSearchResponse extends Message<CodeSearchResponse> {
  /**
   * @generated from field: repeated helixgitpx.search.v1.CodeHit hits = 1;
   */
  hits: CodeHit[] = [];

  /**
   * @generated from field: int64 elapsed_ms = 2;
   */
  elapsedMs = protoInt64.zero;

  constructor(data?: PartialMessage<CodeSearchResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.CodeSearchResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "hits", kind: "message", T: CodeHit, repeated: true },
    { no: 2, name: "elapsed_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CodeSearchResponse {
    return new CodeSearchResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CodeSearchResponse {
    return new CodeSearchResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CodeSearchResponse {
    return new CodeSearchResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CodeSearchResponse | PlainMessage<CodeSearchResponse> | undefined, b: CodeSearchResponse | PlainMessage<CodeSearchResponse> | undefined): boolean {
    return proto3.util.equals(CodeSearchResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.search.v1.CodeHit
 */
export class CodeHit extends Message<CodeHit> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: string path = 2;
   */
  path = "";

  /**
   * @generated from field: int32 line = 3;
   */
  line = 0;

  /**
   * @generated from field: string preview = 4;
   */
  preview = "";

  constructor(data?: PartialMessage<CodeHit>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.CodeHit";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "line", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "preview", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CodeHit {
    return new CodeHit().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CodeHit {
    return new CodeHit().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CodeHit {
    return new CodeHit().fromJsonString(jsonString, options);
  }

  static equals(a: CodeHit | PlainMessage<CodeHit> | undefined, b: CodeHit | PlainMessage<CodeHit> | undefined): boolean {
    return proto3.util.equals(CodeHit, a, b);
  }
}

/**
 * @generated from message helixgitpx.search.v1.IndexStatusRequest
 */
export class IndexStatusRequest extends Message<IndexStatusRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  constructor(data?: PartialMessage<IndexStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.IndexStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexStatusRequest {
    return new IndexStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexStatusRequest {
    return new IndexStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexStatusRequest {
    return new IndexStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IndexStatusRequest | PlainMessage<IndexStatusRequest> | undefined, b: IndexStatusRequest | PlainMessage<IndexStatusRequest> | undefined): boolean {
    return proto3.util.equals(IndexStatusRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.search.v1.IndexStatusResponse
 */
export class IndexStatusResponse extends Message<IndexStatusResponse> {
  /**
   * @generated from field: bool meilisearch_ready = 1;
   */
  meilisearchReady = false;

  /**
   * @generated from field: bool qdrant_ready = 2;
   */
  qdrantReady = false;

  /**
   * @generated from field: bool zoekt_ready = 3;
   */
  zoektReady = false;

  /**
   * @generated from field: int64 keyword_doc_count = 4;
   */
  keywordDocCount = protoInt64.zero;

  /**
   * @generated from field: int64 vector_doc_count = 5;
   */
  vectorDocCount = protoInt64.zero;

  constructor(data?: PartialMessage<IndexStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.search.v1.IndexStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "meilisearch_ready", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "qdrant_ready", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "zoekt_ready", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "keyword_doc_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "vector_doc_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexStatusResponse {
    return new IndexStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexStatusResponse {
    return new IndexStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexStatusResponse {
    return new IndexStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IndexStatusResponse | PlainMessage<IndexStatusResponse> | undefined, b: IndexStatusResponse | PlainMessage<IndexStatusResponse> | undefined): boolean {
    return proto3.util.equals(IndexStatusResponse, a, b);
  }
}

