// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/search/v1/search.proto (package helixgitpx.search.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CodeSearchRequest, CodeSearchResponse, IndexStatusRequest, IndexStatusResponse, SearchRequest, SearchResponse } from "./search_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helixgitpx.search.v1.SearchService
 */
export const SearchService = {
  typeName: "helixgitpx.search.v1.SearchService",
  methods: {
    /**
     * @generated from rpc helixgitpx.search.v1.SearchService.Search
     */
    search: {
      name: "Search",
      I: SearchRequest,
      O: SearchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.search.v1.SearchService.CodeSearch
     */
    codeSearch: {
      name: "CodeSearch",
      I: CodeSearchRequest,
      O: CodeSearchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.search.v1.SearchService.IndexStatus
     */
    indexStatus: {
      name: "IndexStatus",
      I: IndexStatusRequest,
      O: IndexStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

