apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debezium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: "{{ env REPO_URL }}"
    targetRevision: main
    path: impl/helixgitpx-platform/helm/debezium
    helm:
      valueFiles:
        - values.yaml
        - values-{{ env HELIX_ENV | default "local" }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: helix-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
