apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-replica
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: helixgitpx-region-b
  source:
    repoURL: https://github.com/HelixGitpx/HelixGitpx.git
    path: impl/helixgitpx-platform/helm/postgres-replica
    targetRevision: main
    helm:
      releaseName: postgres-replica
  destination:
    server: https://kubernetes.region-b.internal
    namespace: postgres
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
