// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/adapter/v1/adapter.proto (package helixgitpx.adapter.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.adapter.v1.ProviderID
 */
export enum ProviderID {
  /**
   * @generated from enum value: PROVIDER_ID_UNSPECIFIED = 0;
   */
  PROVIDER_ID_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PROVIDER_ID_GITHUB = 1;
   */
  PROVIDER_ID_GITHUB = 1,

  /**
   * @generated from enum value: PROVIDER_ID_GITLAB = 2;
   */
  PROVIDER_ID_GITLAB = 2,

  /**
   * @generated from enum value: PROVIDER_ID_GITEA = 3;
   */
  PROVIDER_ID_GITEA = 3,

  /**
   * @generated from enum value: PROVIDER_ID_GITEE = 4;
   */
  PROVIDER_ID_GITEE = 4,

  /**
   * @generated from enum value: PROVIDER_ID_BITBUCKET = 5;
   */
  PROVIDER_ID_BITBUCKET = 5,

  /**
   * @generated from enum value: PROVIDER_ID_GITFLIC = 6;
   */
  PROVIDER_ID_GITFLIC = 6,

  /**
   * @generated from enum value: PROVIDER_ID_GITVERSE = 7;
   */
  PROVIDER_ID_GITVERSE = 7,

  /**
   * @generated from enum value: PROVIDER_ID_AZURE_DEVOPS = 8;
   */
  PROVIDER_ID_AZURE_DEVOPS = 8,

  /**
   * @generated from enum value: PROVIDER_ID_AWS_CODECOMMIT = 9;
   */
  PROVIDER_ID_AWS_CODECOMMIT = 9,

  /**
   * @generated from enum value: PROVIDER_ID_FORGEJO = 10;
   */
  PROVIDER_ID_FORGEJO = 10,

  /**
   * @generated from enum value: PROVIDER_ID_SOURCEHUT = 11;
   */
  PROVIDER_ID_SOURCEHUT = 11,

  /**
   * @generated from enum value: PROVIDER_ID_GENERIC = 12;
   */
  PROVIDER_ID_GENERIC = 12,
}
// Retrieve enum metadata with: proto3.getEnumType(ProviderID)
proto3.util.setEnumType(ProviderID, "helixgitpx.adapter.v1.ProviderID", [
  { no: 0, name: "PROVIDER_ID_UNSPECIFIED" },
  { no: 1, name: "PROVIDER_ID_GITHUB" },
  { no: 2, name: "PROVIDER_ID_GITLAB" },
  { no: 3, name: "PROVIDER_ID_GITEA" },
  { no: 4, name: "PROVIDER_ID_GITEE" },
  { no: 5, name: "PROVIDER_ID_BITBUCKET" },
  { no: 6, name: "PROVIDER_ID_GITFLIC" },
  { no: 7, name: "PROVIDER_ID_GITVERSE" },
  { no: 8, name: "PROVIDER_ID_AZURE_DEVOPS" },
  { no: 9, name: "PROVIDER_ID_AWS_CODECOMMIT" },
  { no: 10, name: "PROVIDER_ID_FORGEJO" },
  { no: 11, name: "PROVIDER_ID_SOURCEHUT" },
  { no: 12, name: "PROVIDER_ID_GENERIC" },
]);

/**
 * @generated from message helixgitpx.adapter.v1.Provider
 */
export class Provider extends Message<Provider> {
  /**
   * @generated from field: helixgitpx.adapter.v1.ProviderID id = 1;
   */
  id = ProviderID.PROVIDER_ID_UNSPECIFIED;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName = "";

  /**
   * @generated from field: bool write_supported = 3;
   */
  writeSupported = false;

  /**
   * @generated from field: bool webhook_hmac = 4;
   */
  webhookHmac = false;

  /**
   * @generated from field: int32 default_rate_limit_per_minute = 5;
   */
  defaultRateLimitPerMinute = 0;

  constructor(data?: PartialMessage<Provider>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.adapter.v1.Provider";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "enum", T: proto3.getEnumType(ProviderID) },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "write_supported", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "webhook_hmac", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "default_rate_limit_per_minute", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Provider {
    return new Provider().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Provider {
    return new Provider().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Provider {
    return new Provider().fromJsonString(jsonString, options);
  }

  static equals(a: Provider | PlainMessage<Provider> | undefined, b: Provider | PlainMessage<Provider> | undefined): boolean {
    return proto3.util.equals(Provider, a, b);
  }
}

/**
 * @generated from message helixgitpx.adapter.v1.ProviderHealth
 */
export class ProviderHealth extends Message<ProviderHealth> {
  /**
   * @generated from field: helixgitpx.adapter.v1.ProviderID id = 1;
   */
  id = ProviderID.PROVIDER_ID_UNSPECIFIED;

  /**
   * @generated from field: bool healthy = 2;
   */
  healthy = false;

  /**
   * @generated from field: string detail = 3;
   */
  detail = "";

  /**
   * @generated from field: int32 last_status_code = 4;
   */
  lastStatusCode = 0;

  /**
   * @generated from field: int64 last_latency_ms = 5;
   */
  lastLatencyMs = protoInt64.zero;

  constructor(data?: PartialMessage<ProviderHealth>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.adapter.v1.ProviderHealth";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "enum", T: proto3.getEnumType(ProviderID) },
    { no: 2, name: "healthy", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "last_status_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "last_latency_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProviderHealth {
    return new ProviderHealth().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProviderHealth {
    return new ProviderHealth().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProviderHealth {
    return new ProviderHealth().fromJsonString(jsonString, options);
  }

  static equals(a: ProviderHealth | PlainMessage<ProviderHealth> | undefined, b: ProviderHealth | PlainMessage<ProviderHealth> | undefined): boolean {
    return proto3.util.equals(ProviderHealth, a, b);
  }
}

/**
 * @generated from message helixgitpx.adapter.v1.ListProvidersRequest
 */
export class ListProvidersRequest extends Message<ListProvidersRequest> {
  constructor(data?: PartialMessage<ListProvidersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.adapter.v1.ListProvidersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListProvidersRequest {
    return new ListProvidersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListProvidersRequest {
    return new ListProvidersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListProvidersRequest {
    return new ListProvidersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListProvidersRequest | PlainMessage<ListProvidersRequest> | undefined, b: ListProvidersRequest | PlainMessage<ListProvidersRequest> | undefined): boolean {
    return proto3.util.equals(ListProvidersRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.adapter.v1.ListProvidersResponse
 */
export class ListProvidersResponse extends Message<ListProvidersResponse> {
  /**
   * @generated from field: repeated helixgitpx.adapter.v1.Provider providers = 1;
   */
  providers: Provider[] = [];

  constructor(data?: PartialMessage<ListProvidersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.adapter.v1.ListProvidersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "providers", kind: "message", T: Provider, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListProvidersResponse {
    return new ListProvidersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListProvidersResponse {
    return new ListProvidersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListProvidersResponse {
    return new ListProvidersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListProvidersResponse | PlainMessage<ListProvidersResponse> | undefined, b: ListProvidersResponse | PlainMessage<ListProvidersResponse> | undefined): boolean {
    return proto3.util.equals(ListProvidersResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.adapter.v1.ProviderHealthRequest
 */
export class ProviderHealthRequest extends Message<ProviderHealthRequest> {
  /**
   * @generated from field: helixgitpx.adapter.v1.ProviderID id = 1;
   */
  id = ProviderID.PROVIDER_ID_UNSPECIFIED;

  constructor(data?: PartialMessage<ProviderHealthRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.adapter.v1.ProviderHealthRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "enum", T: proto3.getEnumType(ProviderID) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProviderHealthRequest {
    return new ProviderHealthRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProviderHealthRequest {
    return new ProviderHealthRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProviderHealthRequest {
    return new ProviderHealthRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ProviderHealthRequest | PlainMessage<ProviderHealthRequest> | undefined, b: ProviderHealthRequest | PlainMessage<ProviderHealthRequest> | undefined): boolean {
    return proto3.util.equals(ProviderHealthRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.adapter.v1.RotateTokenRequest
 */
export class RotateTokenRequest extends Message<RotateTokenRequest> {
  /**
   * @generated from field: helixgitpx.adapter.v1.ProviderID id = 1;
   */
  id = ProviderID.PROVIDER_ID_UNSPECIFIED;

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * written to Vault, never logged
   *
   * @generated from field: string new_token = 3;
   */
  newToken = "";

  constructor(data?: PartialMessage<RotateTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.adapter.v1.RotateTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "enum", T: proto3.getEnumType(ProviderID) },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "new_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RotateTokenRequest {
    return new RotateTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RotateTokenRequest {
    return new RotateTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RotateTokenRequest {
    return new RotateTokenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RotateTokenRequest | PlainMessage<RotateTokenRequest> | undefined, b: RotateTokenRequest | PlainMessage<RotateTokenRequest> | undefined): boolean {
    return proto3.util.equals(RotateTokenRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.adapter.v1.RotateTokenResponse
 */
export class RotateTokenResponse extends Message<RotateTokenResponse> {
  /**
   * @generated from field: bool rotated = 1;
   */
  rotated = false;

  constructor(data?: PartialMessage<RotateTokenResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.adapter.v1.RotateTokenResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "rotated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RotateTokenResponse {
    return new RotateTokenResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RotateTokenResponse {
    return new RotateTokenResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RotateTokenResponse {
    return new RotateTokenResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RotateTokenResponse | PlainMessage<RotateTokenResponse> | undefined, b: RotateTokenResponse | PlainMessage<RotateTokenResponse> | undefined): boolean {
    return proto3.util.equals(RotateTokenResponse, a, b);
  }
}

