// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/adapter/v1/adapter.proto (package helixgitpx.adapter.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListProvidersRequest, ListProvidersResponse, ProviderHealth, ProviderHealthRequest, RotateTokenRequest, RotateTokenResponse } from "./adapter_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AdapterPoolService manages provider adapters (the 12 Git hosts HelixGitpx
 * federates) and exposes metadata + health per adapter.
 *
 * @generated from service helixgitpx.adapter.v1.AdapterPoolService
 */
export const AdapterPoolService = {
  typeName: "helixgitpx.adapter.v1.AdapterPoolService",
  methods: {
    /**
     * @generated from rpc helixgitpx.adapter.v1.AdapterPoolService.ListProviders
     */
    listProviders: {
      name: "ListProviders",
      I: ListProvidersRequest,
      O: ListProvidersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.adapter.v1.AdapterPoolService.GetProviderHealth
     */
    getProviderHealth: {
      name: "GetProviderHealth",
      I: ProviderHealthRequest,
      O: ProviderHealth,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.adapter.v1.AdapterPoolService.RotateToken
     */
    rotateToken: {
      name: "RotateToken",
      I: RotateTokenRequest,
      O: RotateTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

