apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-policies
  namespace: helix-secrets
data:
  pg-backup-writer.hcl: |
    path "kv/data/minio/cnpg-backups" { capabilities = ["read"] }
  opensearch-backup-writer.hcl: |
    path "kv/data/minio/opensearch-snapshots" { capabilities = ["read"] }
  loki-chunk-writer.hcl: |
    path "kv/data/minio/loki-chunks" { capabilities = ["read"] }
  tempo-trace-writer.hcl: |
    path "kv/data/minio/tempo-traces" { capabilities = ["read"] }
  mimir-block-writer.hcl: |
    path "kv/data/minio/mimir-blocks" { capabilities = ["read"] }
  pyroscope-profile-writer.hcl: |
    path "kv/data/minio/pyroscope-profiles" { capabilities = ["read"] }
  hello.hcl: |
    path "kv/data/hello/*"     { capabilities = ["read"] }
    path "kv/metadata/hello/*" { capabilities = ["list"] }
