// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/collab/v1/collab.proto (package helixgitpx.collab.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message helixgitpx.collab.v1.Document
 */
export class Document extends Message<Document> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * Automerge binary snapshot
   *
   * @generated from field: bytes snapshot = 4;
   */
  snapshot = new Uint8Array(0);

  /**
   * @generated from field: int64 vector_clock = 5;
   */
  vectorClock = protoInt64.zero;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Document>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.collab.v1.Document";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "snapshot", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "vector_clock", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Document {
    return new Document().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Document {
    return new Document().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Document {
    return new Document().fromJsonString(jsonString, options);
  }

  static equals(a: Document | PlainMessage<Document> | undefined, b: Document | PlainMessage<Document> | undefined): boolean {
    return proto3.util.equals(Document, a, b);
  }
}

/**
 * @generated from message helixgitpx.collab.v1.OpenDocRequest
 */
export class OpenDocRequest extends Message<OpenDocRequest> {
  /**
   * @generated from field: string doc_id = 1;
   */
  docId = "";

  /**
   * @generated from field: string actor_id = 2;
   */
  actorId = "";

  constructor(data?: PartialMessage<OpenDocRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.collab.v1.OpenDocRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "doc_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OpenDocRequest {
    return new OpenDocRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OpenDocRequest {
    return new OpenDocRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OpenDocRequest {
    return new OpenDocRequest().fromJsonString(jsonString, options);
  }

  static equals(a: OpenDocRequest | PlainMessage<OpenDocRequest> | undefined, b: OpenDocRequest | PlainMessage<OpenDocRequest> | undefined): boolean {
    return proto3.util.equals(OpenDocRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.collab.v1.DocOp
 */
export class DocOp extends Message<DocOp> {
  /**
   * @generated from field: string doc_id = 1;
   */
  docId = "";

  /**
   * @generated from field: string actor_id = 2;
   */
  actorId = "";

  /**
   * Automerge change bytes
   *
   * @generated from field: bytes change = 3;
   */
  change = new Uint8Array(0);

  /**
   * @generated from field: int64 local_seq = 4;
   */
  localSeq = protoInt64.zero;

  /**
   * @generated from field: google.protobuf.Timestamp at = 5;
   */
  at?: Timestamp;

  constructor(data?: PartialMessage<DocOp>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.collab.v1.DocOp";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "doc_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "change", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "local_seq", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocOp {
    return new DocOp().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocOp {
    return new DocOp().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocOp {
    return new DocOp().fromJsonString(jsonString, options);
  }

  static equals(a: DocOp | PlainMessage<DocOp> | undefined, b: DocOp | PlainMessage<DocOp> | undefined): boolean {
    return proto3.util.equals(DocOp, a, b);
  }
}

/**
 * @generated from message helixgitpx.collab.v1.ListPresenceRequest
 */
export class ListPresenceRequest extends Message<ListPresenceRequest> {
  /**
   * @generated from field: string doc_id = 1;
   */
  docId = "";

  constructor(data?: PartialMessage<ListPresenceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.collab.v1.ListPresenceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "doc_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPresenceRequest {
    return new ListPresenceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPresenceRequest {
    return new ListPresenceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPresenceRequest {
    return new ListPresenceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListPresenceRequest | PlainMessage<ListPresenceRequest> | undefined, b: ListPresenceRequest | PlainMessage<ListPresenceRequest> | undefined): boolean {
    return proto3.util.equals(ListPresenceRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.collab.v1.ListPresenceResponse
 */
export class ListPresenceResponse extends Message<ListPresenceResponse> {
  /**
   * @generated from field: repeated helixgitpx.collab.v1.Presence present = 1;
   */
  present: Presence[] = [];

  constructor(data?: PartialMessage<ListPresenceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.collab.v1.ListPresenceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "present", kind: "message", T: Presence, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPresenceResponse {
    return new ListPresenceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPresenceResponse {
    return new ListPresenceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPresenceResponse {
    return new ListPresenceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListPresenceResponse | PlainMessage<ListPresenceResponse> | undefined, b: ListPresenceResponse | PlainMessage<ListPresenceResponse> | undefined): boolean {
    return proto3.util.equals(ListPresenceResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.collab.v1.Presence
 */
export class Presence extends Message<Presence> {
  /**
   * @generated from field: string actor_id = 1;
   */
  actorId = "";

  /**
   * @generated from field: string display_name = 2;
   */
  displayName = "";

  /**
   * @generated from field: google.protobuf.Timestamp last_seen = 3;
   */
  lastSeen?: Timestamp;

  constructor(data?: PartialMessage<Presence>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.collab.v1.Presence";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "last_seen", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Presence {
    return new Presence().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Presence {
    return new Presence().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Presence {
    return new Presence().fromJsonString(jsonString, options);
  }

  static equals(a: Presence | PlainMessage<Presence> | undefined, b: Presence | PlainMessage<Presence> | undefined): boolean {
    return proto3.util.equals(Presence, a, b);
  }
}

/**
 * @generated from message helixgitpx.collab.v1.CloseDocRequest
 */
export class CloseDocRequest extends Message<CloseDocRequest> {
  /**
   * @generated from field: string doc_id = 1;
   */
  docId = "";

  /**
   * @generated from field: string actor_id = 2;
   */
  actorId = "";

  constructor(data?: PartialMessage<CloseDocRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.collab.v1.CloseDocRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "doc_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CloseDocRequest {
    return new CloseDocRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CloseDocRequest {
    return new CloseDocRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CloseDocRequest {
    return new CloseDocRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CloseDocRequest | PlainMessage<CloseDocRequest> | undefined, b: CloseDocRequest | PlainMessage<CloseDocRequest> | undefined): boolean {
    return proto3.util.equals(CloseDocRequest, a, b);
  }
}

