// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/collab/v1/collab.proto (package helixgitpx.collab.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CloseDocRequest, DocOp, Document, ListPresenceRequest, ListPresenceResponse, OpenDocRequest } from "./collab_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * CollabService owns real-time collaborative document state (Automerge CRDT).
 * Clients open a stream; server broadcasts ops from every connected peer.
 *
 * @generated from service helixgitpx.collab.v1.CollabService
 */
export const CollabService = {
  typeName: "helixgitpx.collab.v1.CollabService",
  methods: {
    /**
     * @generated from rpc helixgitpx.collab.v1.CollabService.OpenDoc
     */
    openDoc: {
      name: "OpenDoc",
      I: OpenDocRequest,
      O: Document,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.collab.v1.CollabService.ApplyOps
     */
    applyOps: {
      name: "ApplyOps",
      I: DocOp,
      O: DocOp,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc helixgitpx.collab.v1.CollabService.ListPresence
     */
    listPresence: {
      name: "ListPresence",
      I: ListPresenceRequest,
      O: ListPresenceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.collab.v1.CollabService.CloseDoc
     */
    closeDoc: {
      name: "CloseDoc",
      I: CloseDocRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

