// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/collab/v1/stubs.proto (package helixgitpx.collab.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/collab/v1/stubs.proto.
 */
export const file_helixgitpx_collab_v1_stubs: GenFile = /*@__PURE__*/
  fileDesc("CiBoZWxpeGdpdHB4L2NvbGxhYi92MS9zdHVicy5wcm90bxIUaGVsaXhnaXRweC5jb2xsYWIudjEiHwoLUGxhY2Vob2xkZXISEAoIcmVzZXJ2ZWQYASABKAlC3wEKGGNvbS5oZWxpeGdpdHB4LmNvbGxhYi52MUIKU3R1YnNQcm90b1ABWkVnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC9jb2xsYWIvdjE7Y29sbGFidjGiAgNIQ1iqAhRIZWxpeGdpdHB4LkNvbGxhYi5WMcoCFEhlbGl4Z2l0cHhcQ29sbGFiXFYx4gIgSGVsaXhnaXRweFxDb2xsYWJcVjFcR1BCTWV0YWRhdGHqAhZIZWxpeGdpdHB4OjpDb2xsYWI6OlYxYgZwcm90bzM");

/**
 * Stub placeholder — real messages and services land in the milestone owning this domain.
 * See proto/README.md for the M1 → Mx ownership table.
 *
 * @generated from message helixgitpx.collab.v1.Placeholder
 */
export type Placeholder = Message<"helixgitpx.collab.v1.Placeholder"> & {
  /**
   * @generated from field: string reserved = 1;
   */
  reserved: string;
};

/**
 * Describes the message helixgitpx.collab.v1.Placeholder.
 * Use `create(PlaceholderSchema)` to create a new message.
 */
export const PlaceholderSchema: GenMessage<Placeholder> = /*@__PURE__*/
  messageDesc(file_helixgitpx_collab_v1_stubs, 0);

