// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/webhook/v1/webhook.proto (package helixgitpx.webhook.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.webhook.v1.DeliveryStatus
 */
export enum DeliveryStatus {
  /**
   * @generated from enum value: DELIVERY_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DELIVERY_STATUS_ACCEPTED = 1;
   */
  ACCEPTED = 1,

  /**
   * HMAC / schema failed
   *
   * @generated from enum value: DELIVERY_STATUS_REJECTED = 2;
   */
  REJECTED = 2,

  /**
   * emitted to Kafka
   *
   * @generated from enum value: DELIVERY_STATUS_PUBLISHED = 3;
   */
  PUBLISHED = 3,

  /**
   * @generated from enum value: DELIVERY_STATUS_DLQ = 4;
   */
  DLQ = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(DeliveryStatus)
proto3.util.setEnumType(DeliveryStatus, "helixgitpx.webhook.v1.DeliveryStatus", [
  { no: 0, name: "DELIVERY_STATUS_UNSPECIFIED" },
  { no: 1, name: "DELIVERY_STATUS_ACCEPTED" },
  { no: 2, name: "DELIVERY_STATUS_REJECTED" },
  { no: 3, name: "DELIVERY_STATUS_PUBLISHED" },
  { no: 4, name: "DELIVERY_STATUS_DLQ" },
]);

/**
 * @generated from message helixgitpx.webhook.v1.Delivery
 */
export class Delivery extends Message<Delivery> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * "github" | "gitlab" | …
   *
   * @generated from field: string provider = 2;
   */
  provider = "";

  /**
   * @generated from field: string event_type = 3;
   */
  eventType = "";

  /**
   * @generated from field: string repo_id = 4;
   */
  repoId = "";

  /**
   * @generated from field: helixgitpx.webhook.v1.DeliveryStatus status = 5;
   */
  status = DeliveryStatus.UNSPECIFIED;

  /**
   * @generated from field: bytes raw_body_hash = 6;
   */
  rawBodyHash = new Uint8Array(0);

  /**
   * @generated from field: string signature = 7;
   */
  signature = "";

  /**
   * @generated from field: google.protobuf.Timestamp received_at = 8;
   */
  receivedAt?: Timestamp;

  /**
   * @generated from field: string kafka_offset = 9;
   */
  kafkaOffset = "";

  constructor(data?: PartialMessage<Delivery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.webhook.v1.Delivery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "event_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "status", kind: "enum", T: proto3.getEnumType(DeliveryStatus) },
    { no: 6, name: "raw_body_hash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 7, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "received_at", kind: "message", T: Timestamp },
    { no: 9, name: "kafka_offset", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Delivery {
    return new Delivery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Delivery {
    return new Delivery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Delivery {
    return new Delivery().fromJsonString(jsonString, options);
  }

  static equals(a: Delivery | PlainMessage<Delivery> | undefined, b: Delivery | PlainMessage<Delivery> | undefined): boolean {
    return proto3.util.equals(Delivery, a, b);
  }
}

/**
 * @generated from message helixgitpx.webhook.v1.ListDeliveriesRequest
 */
export class ListDeliveriesRequest extends Message<ListDeliveriesRequest> {
  /**
   * @generated from field: string provider = 1;
   */
  provider = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * @generated from field: helixgitpx.webhook.v1.DeliveryStatus status = 3;
   */
  status = DeliveryStatus.UNSPECIFIED;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 5;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListDeliveriesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.webhook.v1.ListDeliveriesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(DeliveryStatus) },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDeliveriesRequest {
    return new ListDeliveriesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDeliveriesRequest {
    return new ListDeliveriesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDeliveriesRequest {
    return new ListDeliveriesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListDeliveriesRequest | PlainMessage<ListDeliveriesRequest> | undefined, b: ListDeliveriesRequest | PlainMessage<ListDeliveriesRequest> | undefined): boolean {
    return proto3.util.equals(ListDeliveriesRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.webhook.v1.ListDeliveriesResponse
 */
export class ListDeliveriesResponse extends Message<ListDeliveriesResponse> {
  /**
   * @generated from field: repeated helixgitpx.webhook.v1.Delivery deliveries = 1;
   */
  deliveries: Delivery[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListDeliveriesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.webhook.v1.ListDeliveriesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deliveries", kind: "message", T: Delivery, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDeliveriesResponse {
    return new ListDeliveriesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDeliveriesResponse {
    return new ListDeliveriesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDeliveriesResponse {
    return new ListDeliveriesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListDeliveriesResponse | PlainMessage<ListDeliveriesResponse> | undefined, b: ListDeliveriesResponse | PlainMessage<ListDeliveriesResponse> | undefined): boolean {
    return proto3.util.equals(ListDeliveriesResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.webhook.v1.GetDeliveryRequest
 */
export class GetDeliveryRequest extends Message<GetDeliveryRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetDeliveryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.webhook.v1.GetDeliveryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDeliveryRequest {
    return new GetDeliveryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDeliveryRequest {
    return new GetDeliveryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDeliveryRequest {
    return new GetDeliveryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetDeliveryRequest | PlainMessage<GetDeliveryRequest> | undefined, b: GetDeliveryRequest | PlainMessage<GetDeliveryRequest> | undefined): boolean {
    return proto3.util.equals(GetDeliveryRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.webhook.v1.ReplayRequest
 */
export class ReplayRequest extends Message<ReplayRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<ReplayRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.webhook.v1.ReplayRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReplayRequest {
    return new ReplayRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReplayRequest {
    return new ReplayRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReplayRequest {
    return new ReplayRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReplayRequest | PlainMessage<ReplayRequest> | undefined, b: ReplayRequest | PlainMessage<ReplayRequest> | undefined): boolean {
    return proto3.util.equals(ReplayRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.webhook.v1.RotateSecretRequest
 */
export class RotateSecretRequest extends Message<RotateSecretRequest> {
  /**
   * @generated from field: string provider = 1;
   */
  provider = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  constructor(data?: PartialMessage<RotateSecretRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.webhook.v1.RotateSecretRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RotateSecretRequest {
    return new RotateSecretRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RotateSecretRequest {
    return new RotateSecretRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RotateSecretRequest {
    return new RotateSecretRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RotateSecretRequest | PlainMessage<RotateSecretRequest> | undefined, b: RotateSecretRequest | PlainMessage<RotateSecretRequest> | undefined): boolean {
    return proto3.util.equals(RotateSecretRequest, a, b);
  }
}

