// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/webhook/v1/webhook.proto (package helixgitpx.webhook.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Delivery, GetDeliveryRequest, ListDeliveriesRequest, ListDeliveriesResponse, ReplayRequest, RotateSecretRequest } from "./webhook_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * WebhookGatewayService is the internal RPC surface for the webhook-gateway.
 * Inbound HTTP webhooks from providers are handled on the REST side; this
 * service exposes admin operations (list deliveries, replay, rotate secrets).
 *
 * @generated from service helixgitpx.webhook.v1.WebhookGatewayService
 */
export const WebhookGatewayService = {
  typeName: "helixgitpx.webhook.v1.WebhookGatewayService",
  methods: {
    /**
     * @generated from rpc helixgitpx.webhook.v1.WebhookGatewayService.ListDeliveries
     */
    listDeliveries: {
      name: "ListDeliveries",
      I: ListDeliveriesRequest,
      O: ListDeliveriesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.webhook.v1.WebhookGatewayService.GetDelivery
     */
    getDelivery: {
      name: "GetDelivery",
      I: GetDeliveryRequest,
      O: Delivery,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.webhook.v1.WebhookGatewayService.Replay
     */
    replay: {
      name: "Replay",
      I: ReplayRequest,
      O: Delivery,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.webhook.v1.WebhookGatewayService.RotateSecret
     */
    rotateSecret: {
      name: "RotateSecret",
      I: RotateSecretRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

