[tools]
go = "1.23.4"
node = "20.18.1"
java = "temurin-21.0.5+11"
gradle = "8.10.2"
protoc = "28.3"
"go:github.com/bufbuild/buf/cmd/buf" = "1.47.2"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "1.27.0"
kubectl = "1.31.3"
helm = "3.16.3"
kind = "0.25.0"
k3d = "5.7.5"
skaffold = "2.13.2"
tilt = "0.33.21"
cosign = "2.4.1"
syft = "1.18.0"
grype = "0.85.0"
kyverno-cli = "1.13.2"
"pipx:checkov" = "3.2.334"
"go:github.com/go-delve/delve/cmd/dlv" = "1.23.1"
"go:github.com/pressly/goose/v3/cmd/goose" = "3.22.1"
"go:github.com/go-task/task/v3/cmd/task" = "3.40.0"
"go:mvdan.cc/gofumpt" = "0.7.0"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "1.62.2"
"go:github.com/go-gremlins/gremlins/cmd/gremlins" = "0.5.0"

[env]
GOFLAGS = "-mod=mod"
KUBECONFIG = "{{config_root}}/.kube/config"
