SHELL := /usr/bin/env bash
.PHONY: lint test build image
lint:
	golangci-lint run ./...
test:
	go test -race ./...
build:
	go build -o bin/<<.Name>> ./cmd/<<.Name>>
image:
	docker build -t helixgitpx/<<.Name>>:dev -f deploy/Dockerfile ../..
