apiVersion: v1
kind: Secret
metadata:
  name: minio-root-creds
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | default "admin" | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | default "minioadmin-change-me" | quote }}
