// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/audit/v1/event.proto (package helixgitpx.audit.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuditEvent, GetEventRequest, ListEventsRequest, ListEventsResponse, VerifyMerkleRootRequest, VerifyMerkleRootResponse } from "./event_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AuditService is the query surface. Writes land via the outbox, not through
 * this RPC.
 *
 * @generated from service helixgitpx.audit.v1.AuditService
 */
export const AuditService = {
  typeName: "helixgitpx.audit.v1.AuditService",
  methods: {
    /**
     * @generated from rpc helixgitpx.audit.v1.AuditService.ListEvents
     */
    listEvents: {
      name: "ListEvents",
      I: ListEventsRequest,
      O: ListEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.audit.v1.AuditService.GetEvent
     */
    getEvent: {
      name: "GetEvent",
      I: GetEventRequest,
      O: AuditEvent,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.audit.v1.AuditService.VerifyMerkleRoot
     */
    verifyMerkleRoot: {
      name: "VerifyMerkleRoot",
      I: VerifyMerkleRootRequest,
      O: VerifyMerkleRootResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

