// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/audit/v1/event.proto (package helixgitpx.audit.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Struct, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.audit.v1.Severity
 */
export enum Severity {
  /**
   * @generated from enum value: SEVERITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEVERITY_INFO = 1;
   */
  INFO = 1,

  /**
   * @generated from enum value: SEVERITY_NOTICE = 2;
   */
  NOTICE = 2,

  /**
   * @generated from enum value: SEVERITY_WARNING = 3;
   */
  WARNING = 3,

  /**
   * @generated from enum value: SEVERITY_ERROR = 4;
   */
  ERROR = 4,

  /**
   * @generated from enum value: SEVERITY_CRITICAL = 5;
   */
  CRITICAL = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(Severity)
proto3.util.setEnumType(Severity, "helixgitpx.audit.v1.Severity", [
  { no: 0, name: "SEVERITY_UNSPECIFIED" },
  { no: 1, name: "SEVERITY_INFO" },
  { no: 2, name: "SEVERITY_NOTICE" },
  { no: 3, name: "SEVERITY_WARNING" },
  { no: 4, name: "SEVERITY_ERROR" },
  { no: 5, name: "SEVERITY_CRITICAL" },
]);

/**
 * AuditEvent is the canonical shape emitted to the `audit.events` Kafka topic
 * via the outbox pattern. Every service that mutates tenancy, repos, sync
 * state, policy, or AI outputs publishes AuditEvents.
 *
 * @generated from message helixgitpx.audit.v1.AuditEvent
 */
export class AuditEvent extends Message<AuditEvent> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * "orgteam-service", "repo-service", …
   *
   * @generated from field: string source_service = 2;
   */
  sourceService = "";

  /**
   * dotted verb, e.g. "org.created"
   *
   * @generated from field: string action = 3;
   */
  action = "";

  /**
   * @generated from field: string actor_id = 4;
   */
  actorId = "";

  /**
   * @generated from field: string org_id = 5;
   */
  orgId = "";

  /**
   * optional
   *
   * @generated from field: string repo_id = 6;
   */
  repoId = "";

  /**
   * the subject of the action
   *
   * @generated from field: string target_id = 7;
   */
  targetId = "";

  /**
   * "org", "repo", "pr", "policy", …
   *
   * @generated from field: string target_kind = 8;
   */
  targetKind = "";

  /**
   * @generated from field: google.protobuf.Timestamp at = 9;
   */
  at?: Timestamp;

  /**
   * @generated from field: google.protobuf.Struct metadata = 10;
   */
  metadata?: Struct;

  /**
   * @generated from field: string trace_id = 11;
   */
  traceId = "";

  /**
   * @generated from field: string span_id = 12;
   */
  spanId = "";

  /**
   * @generated from field: helixgitpx.audit.v1.Severity severity = 13;
   */
  severity = Severity.UNSPECIFIED;

  /**
   * present when OPA was consulted
   *
   * @generated from field: string decision_id = 14;
   */
  decisionId = "";

  constructor(data?: PartialMessage<AuditEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.audit.v1.AuditEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "source_service", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "action", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "target_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "target_kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "at", kind: "message", T: Timestamp },
    { no: 10, name: "metadata", kind: "message", T: Struct },
    { no: 11, name: "trace_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "span_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "severity", kind: "enum", T: proto3.getEnumType(Severity) },
    { no: 14, name: "decision_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuditEvent {
    return new AuditEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuditEvent {
    return new AuditEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuditEvent {
    return new AuditEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AuditEvent | PlainMessage<AuditEvent> | undefined, b: AuditEvent | PlainMessage<AuditEvent> | undefined): boolean {
    return proto3.util.equals(AuditEvent, a, b);
  }
}

/**
 * @generated from message helixgitpx.audit.v1.ListEventsRequest
 */
export class ListEventsRequest extends Message<ListEventsRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * @generated from field: helixgitpx.audit.v1.Severity min_severity = 3;
   */
  minSeverity = Severity.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp from = 4;
   */
  from?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp until = 5;
   */
  until?: Timestamp;

  /**
   * @generated from field: int32 page_size = 6;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 7;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.audit.v1.ListEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "min_severity", kind: "enum", T: proto3.getEnumType(Severity) },
    { no: 4, name: "from", kind: "message", T: Timestamp },
    { no: 5, name: "until", kind: "message", T: Timestamp },
    { no: 6, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined, b: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined): boolean {
    return proto3.util.equals(ListEventsRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.audit.v1.ListEventsResponse
 */
export class ListEventsResponse extends Message<ListEventsResponse> {
  /**
   * @generated from field: repeated helixgitpx.audit.v1.AuditEvent events = 1;
   */
  events: AuditEvent[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.audit.v1.ListEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: AuditEvent, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined, b: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined): boolean {
    return proto3.util.equals(ListEventsResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.audit.v1.GetEventRequest
 */
export class GetEventRequest extends Message<GetEventRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.audit.v1.GetEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventRequest {
    return new GetEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventRequest | PlainMessage<GetEventRequest> | undefined, b: GetEventRequest | PlainMessage<GetEventRequest> | undefined): boolean {
    return proto3.util.equals(GetEventRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.audit.v1.VerifyMerkleRootRequest
 */
export class VerifyMerkleRootRequest extends Message<VerifyMerkleRootRequest> {
  /**
   * @generated from field: bytes expected_root = 1;
   */
  expectedRoot = new Uint8Array(0);

  /**
   * @generated from field: google.protobuf.Timestamp as_of = 2;
   */
  asOf?: Timestamp;

  constructor(data?: PartialMessage<VerifyMerkleRootRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.audit.v1.VerifyMerkleRootRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "expected_root", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "as_of", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyMerkleRootRequest {
    return new VerifyMerkleRootRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyMerkleRootRequest {
    return new VerifyMerkleRootRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyMerkleRootRequest {
    return new VerifyMerkleRootRequest().fromJsonString(jsonString, options);
  }

  static equals(a: VerifyMerkleRootRequest | PlainMessage<VerifyMerkleRootRequest> | undefined, b: VerifyMerkleRootRequest | PlainMessage<VerifyMerkleRootRequest> | undefined): boolean {
    return proto3.util.equals(VerifyMerkleRootRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.audit.v1.VerifyMerkleRootResponse
 */
export class VerifyMerkleRootResponse extends Message<VerifyMerkleRootResponse> {
  /**
   * @generated from field: bool verified = 1;
   */
  verified = false;

  /**
   * @generated from field: bytes observed_root = 2;
   */
  observedRoot = new Uint8Array(0);

  /**
   * @generated from field: int64 leaf_count = 3;
   */
  leafCount = protoInt64.zero;

  constructor(data?: PartialMessage<VerifyMerkleRootResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.audit.v1.VerifyMerkleRootResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "observed_root", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "leaf_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyMerkleRootResponse {
    return new VerifyMerkleRootResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyMerkleRootResponse {
    return new VerifyMerkleRootResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyMerkleRootResponse {
    return new VerifyMerkleRootResponse().fromJsonString(jsonString, options);
  }

  static equals(a: VerifyMerkleRootResponse | PlainMessage<VerifyMerkleRootResponse> | undefined, b: VerifyMerkleRootResponse | PlainMessage<VerifyMerkleRootResponse> | undefined): boolean {
    return proto3.util.equals(VerifyMerkleRootResponse, a, b);
  }
}

