// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/billing/v1/billing.proto (package helixgitpx.billing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.billing.v1.Plan
 */
export enum Plan {
  /**
   * @generated from enum value: PLAN_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PLAN_FREE = 1;
   */
  FREE = 1,

  /**
   * @generated from enum value: PLAN_TEAM = 2;
   */
  TEAM = 2,

  /**
   * @generated from enum value: PLAN_SCALE = 3;
   */
  SCALE = 3,

  /**
   * @generated from enum value: PLAN_ENTERPRISE = 4;
   */
  ENTERPRISE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(Plan)
proto3.util.setEnumType(Plan, "helixgitpx.billing.v1.Plan", [
  { no: 0, name: "PLAN_UNSPECIFIED" },
  { no: 1, name: "PLAN_FREE" },
  { no: 2, name: "PLAN_TEAM" },
  { no: 3, name: "PLAN_SCALE" },
  { no: 4, name: "PLAN_ENTERPRISE" },
]);

/**
 * @generated from enum helixgitpx.billing.v1.SubscriptionStatus
 */
export enum SubscriptionStatus {
  /**
   * @generated from enum value: SUBSCRIPTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SUBSCRIPTION_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: SUBSCRIPTION_STATUS_PAST_DUE = 2;
   */
  PAST_DUE = 2,

  /**
   * @generated from enum value: SUBSCRIPTION_STATUS_CANCELED = 3;
   */
  CANCELED = 3,

  /**
   * @generated from enum value: SUBSCRIPTION_STATUS_UNPAID = 4;
   */
  UNPAID = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(SubscriptionStatus)
proto3.util.setEnumType(SubscriptionStatus, "helixgitpx.billing.v1.SubscriptionStatus", [
  { no: 0, name: "SUBSCRIPTION_STATUS_UNSPECIFIED" },
  { no: 1, name: "SUBSCRIPTION_STATUS_ACTIVE" },
  { no: 2, name: "SUBSCRIPTION_STATUS_PAST_DUE" },
  { no: 3, name: "SUBSCRIPTION_STATUS_CANCELED" },
  { no: 4, name: "SUBSCRIPTION_STATUS_UNPAID" },
]);

/**
 * @generated from message helixgitpx.billing.v1.Subscription
 */
export class Subscription extends Message<Subscription> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string org_id = 2;
   */
  orgId = "";

  /**
   * @generated from field: string customer_id = 3;
   */
  customerId = "";

  /**
   * @generated from field: helixgitpx.billing.v1.Plan plan = 4;
   */
  plan = Plan.UNSPECIFIED;

  /**
   * @generated from field: helixgitpx.billing.v1.SubscriptionStatus status = 5;
   */
  status = SubscriptionStatus.UNSPECIFIED;

  /**
   * @generated from field: int32 seats = 6;
   */
  seats = 0;

  /**
   * @generated from field: google.protobuf.Timestamp current_period_end = 7;
   */
  currentPeriodEnd?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp cancelled_at = 8;
   */
  cancelledAt?: Timestamp;

  constructor(data?: PartialMessage<Subscription>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.Subscription";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "plan", kind: "enum", T: proto3.getEnumType(Plan) },
    { no: 5, name: "status", kind: "enum", T: proto3.getEnumType(SubscriptionStatus) },
    { no: 6, name: "seats", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "current_period_end", kind: "message", T: Timestamp },
    { no: 8, name: "cancelled_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Subscription {
    return new Subscription().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Subscription {
    return new Subscription().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Subscription {
    return new Subscription().fromJsonString(jsonString, options);
  }

  static equals(a: Subscription | PlainMessage<Subscription> | undefined, b: Subscription | PlainMessage<Subscription> | undefined): boolean {
    return proto3.util.equals(Subscription, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.Invoice
 */
export class Invoice extends Message<Invoice> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string subscription_id = 2;
   */
  subscriptionId = "";

  /**
   * @generated from field: int64 amount_cents = 3;
   */
  amountCents = protoInt64.zero;

  /**
   * @generated from field: string currency = 4;
   */
  currency = "";

  /**
   * @generated from field: string status = 5;
   */
  status = "";

  /**
   * @generated from field: google.protobuf.Timestamp issued_at = 6;
   */
  issuedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp paid_at = 7;
   */
  paidAt?: Timestamp;

  /**
   * @generated from field: string hosted_url = 8;
   */
  hostedUrl = "";

  constructor(data?: PartialMessage<Invoice>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.Invoice";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subscription_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount_cents", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "issued_at", kind: "message", T: Timestamp },
    { no: 7, name: "paid_at", kind: "message", T: Timestamp },
    { no: 8, name: "hosted_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice {
    return new Invoice().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice {
    return new Invoice().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice {
    return new Invoice().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice | PlainMessage<Invoice> | undefined, b: Invoice | PlainMessage<Invoice> | undefined): boolean {
    return proto3.util.equals(Invoice, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.GetSubscriptionRequest
 */
export class GetSubscriptionRequest extends Message<GetSubscriptionRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  constructor(data?: PartialMessage<GetSubscriptionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.GetSubscriptionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSubscriptionRequest {
    return new GetSubscriptionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSubscriptionRequest {
    return new GetSubscriptionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSubscriptionRequest {
    return new GetSubscriptionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSubscriptionRequest | PlainMessage<GetSubscriptionRequest> | undefined, b: GetSubscriptionRequest | PlainMessage<GetSubscriptionRequest> | undefined): boolean {
    return proto3.util.equals(GetSubscriptionRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.UpgradePlanRequest
 */
export class UpgradePlanRequest extends Message<UpgradePlanRequest> {
  /**
   * @generated from field: string subscription_id = 1;
   */
  subscriptionId = "";

  /**
   * @generated from field: helixgitpx.billing.v1.Plan plan = 2;
   */
  plan = Plan.UNSPECIFIED;

  /**
   * @generated from field: int32 seats = 3;
   */
  seats = 0;

  constructor(data?: PartialMessage<UpgradePlanRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.UpgradePlanRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "plan", kind: "enum", T: proto3.getEnumType(Plan) },
    { no: 3, name: "seats", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpgradePlanRequest {
    return new UpgradePlanRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpgradePlanRequest {
    return new UpgradePlanRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpgradePlanRequest {
    return new UpgradePlanRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpgradePlanRequest | PlainMessage<UpgradePlanRequest> | undefined, b: UpgradePlanRequest | PlainMessage<UpgradePlanRequest> | undefined): boolean {
    return proto3.util.equals(UpgradePlanRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.DowngradePlanRequest
 */
export class DowngradePlanRequest extends Message<DowngradePlanRequest> {
  /**
   * @generated from field: string subscription_id = 1;
   */
  subscriptionId = "";

  /**
   * @generated from field: helixgitpx.billing.v1.Plan plan = 2;
   */
  plan = Plan.UNSPECIFIED;

  constructor(data?: PartialMessage<DowngradePlanRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.DowngradePlanRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "plan", kind: "enum", T: proto3.getEnumType(Plan) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DowngradePlanRequest {
    return new DowngradePlanRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DowngradePlanRequest {
    return new DowngradePlanRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DowngradePlanRequest {
    return new DowngradePlanRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DowngradePlanRequest | PlainMessage<DowngradePlanRequest> | undefined, b: DowngradePlanRequest | PlainMessage<DowngradePlanRequest> | undefined): boolean {
    return proto3.util.equals(DowngradePlanRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.CancelSubscriptionRequest
 */
export class CancelSubscriptionRequest extends Message<CancelSubscriptionRequest> {
  /**
   * @generated from field: string subscription_id = 1;
   */
  subscriptionId = "";

  /**
   * @generated from field: bool immediate = 2;
   */
  immediate = false;

  constructor(data?: PartialMessage<CancelSubscriptionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.CancelSubscriptionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "immediate", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelSubscriptionRequest {
    return new CancelSubscriptionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelSubscriptionRequest {
    return new CancelSubscriptionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelSubscriptionRequest {
    return new CancelSubscriptionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelSubscriptionRequest | PlainMessage<CancelSubscriptionRequest> | undefined, b: CancelSubscriptionRequest | PlainMessage<CancelSubscriptionRequest> | undefined): boolean {
    return proto3.util.equals(CancelSubscriptionRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.ListInvoicesRequest
 */
export class ListInvoicesRequest extends Message<ListInvoicesRequest> {
  /**
   * @generated from field: string subscription_id = 1;
   */
  subscriptionId = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<ListInvoicesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.ListInvoicesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListInvoicesRequest {
    return new ListInvoicesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListInvoicesRequest {
    return new ListInvoicesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListInvoicesRequest {
    return new ListInvoicesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListInvoicesRequest | PlainMessage<ListInvoicesRequest> | undefined, b: ListInvoicesRequest | PlainMessage<ListInvoicesRequest> | undefined): boolean {
    return proto3.util.equals(ListInvoicesRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.ListInvoicesResponse
 */
export class ListInvoicesResponse extends Message<ListInvoicesResponse> {
  /**
   * @generated from field: repeated helixgitpx.billing.v1.Invoice invoices = 1;
   */
  invoices: Invoice[] = [];

  constructor(data?: PartialMessage<ListInvoicesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.ListInvoicesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "invoices", kind: "message", T: Invoice, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListInvoicesResponse {
    return new ListInvoicesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListInvoicesResponse {
    return new ListInvoicesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListInvoicesResponse {
    return new ListInvoicesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListInvoicesResponse | PlainMessage<ListInvoicesResponse> | undefined, b: ListInvoicesResponse | PlainMessage<ListInvoicesResponse> | undefined): boolean {
    return proto3.util.equals(ListInvoicesResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.DownloadInvoiceRequest
 */
export class DownloadInvoiceRequest extends Message<DownloadInvoiceRequest> {
  /**
   * @generated from field: string invoice_id = 1;
   */
  invoiceId = "";

  constructor(data?: PartialMessage<DownloadInvoiceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.DownloadInvoiceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "invoice_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadInvoiceRequest {
    return new DownloadInvoiceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadInvoiceRequest {
    return new DownloadInvoiceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadInvoiceRequest {
    return new DownloadInvoiceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadInvoiceRequest | PlainMessage<DownloadInvoiceRequest> | undefined, b: DownloadInvoiceRequest | PlainMessage<DownloadInvoiceRequest> | undefined): boolean {
    return proto3.util.equals(DownloadInvoiceRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.billing.v1.InvoiceDownload
 */
export class InvoiceDownload extends Message<InvoiceDownload> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: bytes pdf = 2;
   */
  pdf = new Uint8Array(0);

  constructor(data?: PartialMessage<InvoiceDownload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.billing.v1.InvoiceDownload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pdf", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InvoiceDownload {
    return new InvoiceDownload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InvoiceDownload {
    return new InvoiceDownload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InvoiceDownload {
    return new InvoiceDownload().fromJsonString(jsonString, options);
  }

  static equals(a: InvoiceDownload | PlainMessage<InvoiceDownload> | undefined, b: InvoiceDownload | PlainMessage<InvoiceDownload> | undefined): boolean {
    return proto3.util.equals(InvoiceDownload, a, b);
  }
}

