// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/billing/v1/billing.proto (package helixgitpx.billing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelSubscriptionRequest, DowngradePlanRequest, DownloadInvoiceRequest, GetSubscriptionRequest, InvoiceDownload, ListInvoicesRequest, ListInvoicesResponse, Subscription, UpgradePlanRequest } from "./billing_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * BillingService exposes plan management. Wraps Stripe; other PSPs pluggable
 * via the internal provider.Provider interface.
 *
 * @generated from service helixgitpx.billing.v1.BillingService
 */
export const BillingService = {
  typeName: "helixgitpx.billing.v1.BillingService",
  methods: {
    /**
     * @generated from rpc helixgitpx.billing.v1.BillingService.GetSubscription
     */
    getSubscription: {
      name: "GetSubscription",
      I: GetSubscriptionRequest,
      O: Subscription,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.billing.v1.BillingService.UpgradePlan
     */
    upgradePlan: {
      name: "UpgradePlan",
      I: UpgradePlanRequest,
      O: Subscription,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.billing.v1.BillingService.DowngradePlan
     */
    downgradePlan: {
      name: "DowngradePlan",
      I: DowngradePlanRequest,
      O: Subscription,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.billing.v1.BillingService.CancelSubscription
     */
    cancelSubscription: {
      name: "CancelSubscription",
      I: CancelSubscriptionRequest,
      O: Subscription,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.billing.v1.BillingService.ListInvoices
     */
    listInvoices: {
      name: "ListInvoices",
      I: ListInvoicesRequest,
      O: ListInvoicesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.billing.v1.BillingService.DownloadInvoice
     */
    downloadInvoice: {
      name: "DownloadInvoice",
      I: DownloadInvoiceRequest,
      O: InvoiceDownload,
      kind: MethodKind.Unary,
    },
  }
} as const;

