# syntax=docker/dockerfile:1.7
FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
WORKDIR /src/services/<<.Name>>
RUN CGO_ENABLED=0 GOFLAGS=-mod=mod go build -trimpath -ldflags="-s -w" -o /out/<<.Name>> ./cmd/<<.Name>>

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/<<.Name>> /app/<<.Name>>
USER nonroot
ENTRYPOINT ["/app/<<.Name>>"]
LABEL org.opencontainers.image.title="<<.Name>>"
LABEL org.opencontainers.image.source="https://github.com/helixgitpx/helixgitpx"
