// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/team/v1/team.proto (package helixgitpx.team.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddMemberRequest, CreateTeamRequest, DeleteTeamRequest, GetTeamRequest, ListMembersRequest, ListMembersResponse, ListTeamsRequest, ListTeamsResponse, Membership, RemoveMemberRequest, Team, UpdateMemberRoleRequest, UpdateTeamRequest } from "./team_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helixgitpx.team.v1.TeamService
 */
export const TeamService = {
  typeName: "helixgitpx.team.v1.TeamService",
  methods: {
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.Create
     */
    create: {
      name: "Create",
      I: CreateTeamRequest,
      O: Team,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.Get
     */
    get: {
      name: "Get",
      I: GetTeamRequest,
      O: Team,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.List
     */
    list: {
      name: "List",
      I: ListTeamsRequest,
      O: ListTeamsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.Update
     */
    update: {
      name: "Update",
      I: UpdateTeamRequest,
      O: Team,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteTeamRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.AddMember
     */
    addMember: {
      name: "AddMember",
      I: AddMemberRequest,
      O: Membership,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.RemoveMember
     */
    removeMember: {
      name: "RemoveMember",
      I: RemoveMemberRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.UpdateMemberRole
     */
    updateMemberRole: {
      name: "UpdateMemberRole",
      I: UpdateMemberRoleRequest,
      O: Membership,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.team.v1.TeamService.ListMembers
     */
    listMembers: {
      name: "ListMembers",
      I: ListMembersRequest,
      O: ListMembersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

