// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/conflict/v1/conflict.proto (package helixgitpx.conflict.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.conflict.v1.ConflictKind
 */
export enum ConflictKind {
  /**
   * @generated from enum value: CONFLICT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * two upstreams have different HEADs
   *
   * @generated from enum value: CONFLICT_KIND_REF_DIVERGENCE = 1;
   */
  REF_DIVERGENCE = 1,

  /**
   * @generated from enum value: CONFLICT_KIND_LABEL_RACE = 2;
   */
  LABEL_RACE = 2,

  /**
   * @generated from enum value: CONFLICT_KIND_RENAME_COLLISION = 3;
   */
  RENAME_COLLISION = 3,

  /**
   * @generated from enum value: CONFLICT_KIND_META_DRIFT = 4;
   */
  META_DRIFT = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(ConflictKind)
proto3.util.setEnumType(ConflictKind, "helixgitpx.conflict.v1.ConflictKind", [
  { no: 0, name: "CONFLICT_KIND_UNSPECIFIED" },
  { no: 1, name: "CONFLICT_KIND_REF_DIVERGENCE" },
  { no: 2, name: "CONFLICT_KIND_LABEL_RACE" },
  { no: 3, name: "CONFLICT_KIND_RENAME_COLLISION" },
  { no: 4, name: "CONFLICT_KIND_META_DRIFT" },
]);

/**
 * @generated from enum helixgitpx.conflict.v1.ConflictStatus
 */
export enum ConflictStatus {
  /**
   * @generated from enum value: CONFLICT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONFLICT_STATUS_OPEN = 1;
   */
  OPEN = 1,

  /**
   * @generated from enum value: CONFLICT_STATUS_PROPOSED = 2;
   */
  PROPOSED = 2,

  /**
   * @generated from enum value: CONFLICT_STATUS_RESOLVED = 3;
   */
  RESOLVED = 3,

  /**
   * @generated from enum value: CONFLICT_STATUS_REJECTED = 4;
   */
  REJECTED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(ConflictStatus)
proto3.util.setEnumType(ConflictStatus, "helixgitpx.conflict.v1.ConflictStatus", [
  { no: 0, name: "CONFLICT_STATUS_UNSPECIFIED" },
  { no: 1, name: "CONFLICT_STATUS_OPEN" },
  { no: 2, name: "CONFLICT_STATUS_PROPOSED" },
  { no: 3, name: "CONFLICT_STATUS_RESOLVED" },
  { no: 4, name: "CONFLICT_STATUS_REJECTED" },
]);

/**
 * @generated from message helixgitpx.conflict.v1.Conflict
 */
export class Conflict extends Message<Conflict> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * @generated from field: helixgitpx.conflict.v1.ConflictKind kind = 3;
   */
  kind = ConflictKind.UNSPECIFIED;

  /**
   * @generated from field: helixgitpx.conflict.v1.ConflictStatus status = 4;
   */
  status = ConflictStatus.UNSPECIFIED;

  /**
   * @generated from field: string description = 5;
   */
  description = "";

  /**
   * @generated from field: repeated string involved_upstreams = 6;
   */
  involvedUpstreams: string[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp detected_at = 7;
   */
  detectedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp resolved_at = 8;
   */
  resolvedAt?: Timestamp;

  /**
   * @generated from field: helixgitpx.conflict.v1.Resolution proposed = 9;
   */
  proposed?: Resolution;

  constructor(data?: PartialMessage<Conflict>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.Conflict";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "kind", kind: "enum", T: proto3.getEnumType(ConflictKind) },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(ConflictStatus) },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "involved_upstreams", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "detected_at", kind: "message", T: Timestamp },
    { no: 8, name: "resolved_at", kind: "message", T: Timestamp },
    { no: 9, name: "proposed", kind: "message", T: Resolution },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Conflict {
    return new Conflict().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Conflict {
    return new Conflict().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Conflict {
    return new Conflict().fromJsonString(jsonString, options);
  }

  static equals(a: Conflict | PlainMessage<Conflict> | undefined, b: Conflict | PlainMessage<Conflict> | undefined): boolean {
    return proto3.util.equals(Conflict, a, b);
  }
}

/**
 * @generated from message helixgitpx.conflict.v1.Resolution
 */
export class Resolution extends Message<Resolution> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * "ai" | "human"
   *
   * @generated from field: string source = 2;
   */
  source = "";

  /**
   * @generated from field: string rationale = 3;
   */
  rationale = "";

  /**
   * unified diff or Automerge change
   *
   * @generated from field: bytes patch = 4;
   */
  patch = new Uint8Array(0);

  /**
   * @generated from field: google.protobuf.Timestamp proposed_at = 5;
   */
  proposedAt?: Timestamp;

  constructor(data?: PartialMessage<Resolution>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.Resolution";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "rationale", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "patch", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "proposed_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Resolution {
    return new Resolution().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Resolution {
    return new Resolution().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Resolution {
    return new Resolution().fromJsonString(jsonString, options);
  }

  static equals(a: Resolution | PlainMessage<Resolution> | undefined, b: Resolution | PlainMessage<Resolution> | undefined): boolean {
    return proto3.util.equals(Resolution, a, b);
  }
}

/**
 * @generated from message helixgitpx.conflict.v1.ListConflictsRequest
 */
export class ListConflictsRequest extends Message<ListConflictsRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * @generated from field: helixgitpx.conflict.v1.ConflictStatus status = 3;
   */
  status = ConflictStatus.UNSPECIFIED;

  /**
   * @generated from field: int32 page_size = 4;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 5;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListConflictsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.ListConflictsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(ConflictStatus) },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListConflictsRequest {
    return new ListConflictsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListConflictsRequest {
    return new ListConflictsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListConflictsRequest {
    return new ListConflictsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListConflictsRequest | PlainMessage<ListConflictsRequest> | undefined, b: ListConflictsRequest | PlainMessage<ListConflictsRequest> | undefined): boolean {
    return proto3.util.equals(ListConflictsRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.conflict.v1.ListConflictsResponse
 */
export class ListConflictsResponse extends Message<ListConflictsResponse> {
  /**
   * @generated from field: repeated helixgitpx.conflict.v1.Conflict conflicts = 1;
   */
  conflicts: Conflict[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListConflictsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.ListConflictsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conflicts", kind: "message", T: Conflict, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListConflictsResponse {
    return new ListConflictsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListConflictsResponse {
    return new ListConflictsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListConflictsResponse {
    return new ListConflictsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListConflictsResponse | PlainMessage<ListConflictsResponse> | undefined, b: ListConflictsResponse | PlainMessage<ListConflictsResponse> | undefined): boolean {
    return proto3.util.equals(ListConflictsResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.conflict.v1.GetConflictRequest
 */
export class GetConflictRequest extends Message<GetConflictRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetConflictRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.GetConflictRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetConflictRequest {
    return new GetConflictRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetConflictRequest {
    return new GetConflictRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetConflictRequest {
    return new GetConflictRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetConflictRequest | PlainMessage<GetConflictRequest> | undefined, b: GetConflictRequest | PlainMessage<GetConflictRequest> | undefined): boolean {
    return proto3.util.equals(GetConflictRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.conflict.v1.ProposeResolutionRequest
 */
export class ProposeResolutionRequest extends Message<ProposeResolutionRequest> {
  /**
   * @generated from field: string conflict_id = 1;
   */
  conflictId = "";

  /**
   * @generated from field: bool use_ai = 2;
   */
  useAi = false;

  constructor(data?: PartialMessage<ProposeResolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.ProposeResolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conflict_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "use_ai", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProposeResolutionRequest {
    return new ProposeResolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProposeResolutionRequest {
    return new ProposeResolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProposeResolutionRequest {
    return new ProposeResolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ProposeResolutionRequest | PlainMessage<ProposeResolutionRequest> | undefined, b: ProposeResolutionRequest | PlainMessage<ProposeResolutionRequest> | undefined): boolean {
    return proto3.util.equals(ProposeResolutionRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.conflict.v1.AcceptResolutionRequest
 */
export class AcceptResolutionRequest extends Message<AcceptResolutionRequest> {
  /**
   * @generated from field: string conflict_id = 1;
   */
  conflictId = "";

  /**
   * @generated from field: string resolution_id = 2;
   */
  resolutionId = "";

  constructor(data?: PartialMessage<AcceptResolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.AcceptResolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conflict_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "resolution_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AcceptResolutionRequest {
    return new AcceptResolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AcceptResolutionRequest {
    return new AcceptResolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AcceptResolutionRequest {
    return new AcceptResolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AcceptResolutionRequest | PlainMessage<AcceptResolutionRequest> | undefined, b: AcceptResolutionRequest | PlainMessage<AcceptResolutionRequest> | undefined): boolean {
    return proto3.util.equals(AcceptResolutionRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.conflict.v1.RejectResolutionRequest
 */
export class RejectResolutionRequest extends Message<RejectResolutionRequest> {
  /**
   * @generated from field: string conflict_id = 1;
   */
  conflictId = "";

  /**
   * @generated from field: string resolution_id = 2;
   */
  resolutionId = "";

  /**
   * @generated from field: string reason = 3;
   */
  reason = "";

  constructor(data?: PartialMessage<RejectResolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.conflict.v1.RejectResolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conflict_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "resolution_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RejectResolutionRequest {
    return new RejectResolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RejectResolutionRequest {
    return new RejectResolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RejectResolutionRequest {
    return new RejectResolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RejectResolutionRequest | PlainMessage<RejectResolutionRequest> | undefined, b: RejectResolutionRequest | PlainMessage<RejectResolutionRequest> | undefined): boolean {
    return proto3.util.equals(RejectResolutionRequest, a, b);
  }
}

