// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/conflict/v1/conflict.proto (package helixgitpx.conflict.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AcceptResolutionRequest, Conflict, GetConflictRequest, ListConflictsRequest, ListConflictsResponse, ProposeResolutionRequest, RejectResolutionRequest, Resolution } from "./conflict_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ConflictService exposes the conflict inbox + human-review flow.
 * Detection runs async via sync-orchestrator; this service is the UI surface.
 *
 * @generated from service helixgitpx.conflict.v1.ConflictService
 */
export const ConflictService = {
  typeName: "helixgitpx.conflict.v1.ConflictService",
  methods: {
    /**
     * @generated from rpc helixgitpx.conflict.v1.ConflictService.List
     */
    list: {
      name: "List",
      I: ListConflictsRequest,
      O: ListConflictsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.conflict.v1.ConflictService.Get
     */
    get: {
      name: "Get",
      I: GetConflictRequest,
      O: Conflict,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.conflict.v1.ConflictService.ProposeResolution
     */
    proposeResolution: {
      name: "ProposeResolution",
      I: ProposeResolutionRequest,
      O: Resolution,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.conflict.v1.ConflictService.AcceptResolution
     */
    acceptResolution: {
      name: "AcceptResolution",
      I: AcceptResolutionRequest,
      O: Conflict,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.conflict.v1.ConflictService.RejectResolution
     */
    rejectResolution: {
      name: "RejectResolution",
      I: RejectResolutionRequest,
      O: Conflict,
      kind: MethodKind.Unary,
    },
  }
} as const;

