// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/conflict/v1/stubs.proto (package helixgitpx.conflict.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/conflict/v1/stubs.proto.
 */
export const file_helixgitpx_conflict_v1_stubs: GenFile = /*@__PURE__*/
  fileDesc("CiJoZWxpeGdpdHB4L2NvbmZsaWN0L3YxL3N0dWJzLnByb3RvEhZoZWxpeGdpdHB4LmNvbmZsaWN0LnYxIh8KC1BsYWNlaG9sZGVyEhAKCHJlc2VydmVkGAEgASgJQu0BChpjb20uaGVsaXhnaXRweC5jb25mbGljdC52MUIKU3R1YnNQcm90b1ABWklnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC9jb25mbGljdC92MTtjb25mbGljdHYxogIDSENYqgIWSGVsaXhnaXRweC5Db25mbGljdC5WMcoCFkhlbGl4Z2l0cHhcQ29uZmxpY3RcVjHiAiJIZWxpeGdpdHB4XENvbmZsaWN0XFYxXEdQQk1ldGFkYXRh6gIYSGVsaXhnaXRweDo6Q29uZmxpY3Q6OlYxYgZwcm90bzM");

/**
 * Stub placeholder — real messages and services land in the milestone owning this domain.
 * See proto/README.md for the M1 → Mx ownership table.
 *
 * @generated from message helixgitpx.conflict.v1.Placeholder
 */
export type Placeholder = Message<"helixgitpx.conflict.v1.Placeholder"> & {
  /**
   * @generated from field: string reserved = 1;
   */
  reserved: string;
};

/**
 * Describes the message helixgitpx.conflict.v1.Placeholder.
 * Use `create(PlaceholderSchema)` to create a new message.
 */
export const PlaceholderSchema: GenMessage<Placeholder> = /*@__PURE__*/
  messageDesc(file_helixgitpx_conflict_v1_stubs, 0);

