// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/hello/v1/hello.proto (package helixgitpx.hello.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SayHelloRequest, SayHelloResponse } from "./hello_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * HelloService is the spine service for M1 Foundation.
 * It exercises platform/{grpc,gin,pg,redis,kafka} end-to-end.
 *
 * REST binding is implemented directly by the Gin router in services/hello
 * rather than via google.api.http annotations, so this module has no BSR
 * dependency on googleapis. Later milestones may re-introduce it once a
 * grpc-gateway codegen path is wired.
 *
 * @generated from service helixgitpx.hello.v1.HelloService
 */
export const HelloService = {
  typeName: "helixgitpx.hello.v1.HelloService",
  methods: {
    /**
     * SayHello returns a greeting and (as a side effect) increments a counter
     * in Postgres, caches the last greeting in Redis, and emits hello.said to Kafka.
     *
     * @generated from rpc helixgitpx.hello.v1.HelloService.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: SayHelloRequest,
      O: SayHelloResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

