// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/hello/v1/hello.proto (package helixgitpx.hello.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/hello/v1/hello.proto.
 */
export const file_helixgitpx_hello_v1_hello: GenFile = /*@__PURE__*/
  fileDesc("Ch9oZWxpeGdpdHB4L2hlbGxvL3YxL2hlbGxvLnByb3RvEhNoZWxpeGdpdHB4LmhlbGxvLnYxIh8KD1NheUhlbGxvUmVxdWVzdBIMCgRuYW1lGAEgASgJIjMKEFNheUhlbGxvUmVzcG9uc2USEAoIZ3JlZXRpbmcYASABKAkSDQoFY291bnQYAiABKAMyaQoMSGVsbG9TZXJ2aWNlElkKCFNheUhlbGxvEiQuaGVsaXhnaXRweC5oZWxsby52MS5TYXlIZWxsb1JlcXVlc3QaJS5oZWxpeGdpdHB4LmhlbGxvLnYxLlNheUhlbGxvUmVzcG9uc2UiAELYAQoXY29tLmhlbGl4Z2l0cHguaGVsbG8udjFCCkhlbGxvUHJvdG9QAVpDZ2l0aHViLmNvbS9oZWxpeGdpdHB4L2hlbGl4Z2l0cHgvZ2VuL2dvL2hlbGl4Z2l0cHgvaGVsbG8vdjE7aGVsbG92MaICA0hIWKoCE0hlbGl4Z2l0cHguSGVsbG8uVjHKAhNIZWxpeGdpdHB4XEhlbGxvXFYx4gIfSGVsaXhnaXRweFxIZWxsb1xWMVxHUEJNZXRhZGF0YeoCFUhlbGl4Z2l0cHg6OkhlbGxvOjpWMWIGcHJvdG8z");

/**
 * @generated from message helixgitpx.hello.v1.SayHelloRequest
 */
export type SayHelloRequest = Message<"helixgitpx.hello.v1.SayHelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message helixgitpx.hello.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema: GenMessage<SayHelloRequest> = /*@__PURE__*/
  messageDesc(file_helixgitpx_hello_v1_hello, 0);

/**
 * @generated from message helixgitpx.hello.v1.SayHelloResponse
 */
export type SayHelloResponse = Message<"helixgitpx.hello.v1.SayHelloResponse"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;

  /**
   * @generated from field: int64 count = 2;
   */
  count: bigint;
};

/**
 * Describes the message helixgitpx.hello.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema: GenMessage<SayHelloResponse> = /*@__PURE__*/
  messageDesc(file_helixgitpx_hello_v1_hello, 1);

/**
 * HelloService is the spine service for M1 Foundation.
 * It exercises platform/{grpc,gin,pg,redis,kafka} end-to-end.
 *
 * REST binding is implemented directly by the Gin router in services/hello
 * rather than via google.api.http annotations, so this module has no BSR
 * dependency on googleapis. Later milestones may re-introduce it once a
 * grpc-gateway codegen path is wired.
 *
 * @generated from service helixgitpx.hello.v1.HelloService
 */
export const HelloService: GenService<{
  /**
   * SayHello returns a greeting and (as a side effect) increments a counter
   * in Postgres, caches the last greeting in Redis, and emits hello.said to Kafka.
   *
   * @generated from rpc helixgitpx.hello.v1.HelloService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof SayHelloRequestSchema;
    output: typeof SayHelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_helixgitpx_hello_v1_hello, 0);

