// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/common/v1/errors.proto (package helixgitpx.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Problem mirrors the RFC 7807 problem-details payload used by HelixGitpx REST
 * responses. gRPC clients receive equivalent information via status details.
 *
 * @generated from message helixgitpx.common.v1.Problem
 */
export class Problem extends Message<Problem> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: int32 status = 3;
   */
  status = 0;

  /**
   * @generated from field: string detail = 4;
   */
  detail = "";

  /**
   * @generated from field: string instance = 5;
   */
  instance = "";

  /**
   * @generated from field: string domain = 6;
   */
  domain = "";

  /**
   * @generated from field: string code = 7;
   */
  code = "";

  /**
   * @generated from field: map<string, string> errors = 8;
   */
  errors: { [key: string]: string } = {};

  constructor(data?: PartialMessage<Problem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.common.v1.Problem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "instance", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "domain", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "errors", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Problem {
    return new Problem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Problem {
    return new Problem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Problem {
    return new Problem().fromJsonString(jsonString, options);
  }

  static equals(a: Problem | PlainMessage<Problem> | undefined, b: Problem | PlainMessage<Problem> | undefined): boolean {
    return proto3.util.equals(Problem, a, b);
  }
}

