// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/common/v1/errors.proto (package helixgitpx.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/common/v1/errors.proto.
 */
export const file_helixgitpx_common_v1_errors: GenFile = /*@__PURE__*/
  fileDesc("CiFoZWxpeGdpdHB4L2NvbW1vbi92MS9lcnJvcnMucHJvdG8SFGhlbGl4Z2l0cHguY29tbW9uLnYxIuABCgdQcm9ibGVtEgwKBHR5cGUYASABKAkSDQoFdGl0bGUYAiABKAkSDgoGc3RhdHVzGAMgASgFEg4KBmRldGFpbBgEIAEoCRIQCghpbnN0YW5jZRgFIAEoCRIOCgZkb21haW4YBiABKAkSDAoEY29kZRgHIAEoCRI5CgZlcnJvcnMYCCADKAsyKS5oZWxpeGdpdHB4LmNvbW1vbi52MS5Qcm9ibGVtLkVycm9yc0VudHJ5Gi0KC0Vycm9yc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFC4AEKGGNvbS5oZWxpeGdpdHB4LmNvbW1vbi52MUILRXJyb3JzUHJvdG9QAVpFZ2l0aHViLmNvbS9oZWxpeGdpdHB4L2hlbGl4Z2l0cHgvZ2VuL2dvL2hlbGl4Z2l0cHgvY29tbW9uL3YxO2NvbW1vbnYxogIDSENYqgIUSGVsaXhnaXRweC5Db21tb24uVjHKAhRIZWxpeGdpdHB4XENvbW1vblxWMeICIEhlbGl4Z2l0cHhcQ29tbW9uXFYxXEdQQk1ldGFkYXRh6gIWSGVsaXhnaXRweDo6Q29tbW9uOjpWMWIGcHJvdG8z");

/**
 * Problem mirrors the RFC 7807 problem-details payload used by HelixGitpx REST
 * responses. gRPC clients receive equivalent information via status details.
 *
 * @generated from message helixgitpx.common.v1.Problem
 */
export type Problem = Message<"helixgitpx.common.v1.Problem"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: int32 status = 3;
   */
  status: number;

  /**
   * @generated from field: string detail = 4;
   */
  detail: string;

  /**
   * @generated from field: string instance = 5;
   */
  instance: string;

  /**
   * @generated from field: string domain = 6;
   */
  domain: string;

  /**
   * @generated from field: string code = 7;
   */
  code: string;

  /**
   * @generated from field: map<string, string> errors = 8;
   */
  errors: { [key: string]: string };
};

/**
 * Describes the message helixgitpx.common.v1.Problem.
 * Use `create(ProblemSchema)` to create a new message.
 */
export const ProblemSchema: GenMessage<Problem> = /*@__PURE__*/
  messageDesc(file_helixgitpx_common_v1_errors, 0);

