// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/common/v1/pagination.proto (package helixgitpx.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/common/v1/pagination.proto.
 */
export const file_helixgitpx_common_v1_pagination: GenFile = /*@__PURE__*/
  fileDesc("CiVoZWxpeGdpdHB4L2NvbW1vbi92MS9wYWdpbmF0aW9uLnByb3RvEhRoZWxpeGdpdHB4LmNvbW1vbi52MSI0CgtQYWdlUmVxdWVzdBIRCglwYWdlX3NpemUYASABKAUSEgoKcGFnZV90b2tlbhgCIAEoCSI2CgxQYWdlUmVzcG9uc2USFwoPbmV4dF9wYWdlX3Rva2VuGAEgASgJEg0KBXRvdGFsGAIgASgFQuQBChhjb20uaGVsaXhnaXRweC5jb21tb24udjFCD1BhZ2luYXRpb25Qcm90b1ABWkVnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC9jb21tb24vdjE7Y29tbW9udjGiAgNIQ1iqAhRIZWxpeGdpdHB4LkNvbW1vbi5WMcoCFEhlbGl4Z2l0cHhcQ29tbW9uXFYx4gIgSGVsaXhnaXRweFxDb21tb25cVjFcR1BCTWV0YWRhdGHqAhZIZWxpeGdpdHB4OjpDb21tb246OlYxYgZwcm90bzM");

/**
 * @generated from message helixgitpx.common.v1.PageRequest
 */
export type PageRequest = Message<"helixgitpx.common.v1.PageRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message helixgitpx.common.v1.PageRequest.
 * Use `create(PageRequestSchema)` to create a new message.
 */
export const PageRequestSchema: GenMessage<PageRequest> = /*@__PURE__*/
  messageDesc(file_helixgitpx_common_v1_pagination, 0);

/**
 * @generated from message helixgitpx.common.v1.PageResponse
 */
export type PageResponse = Message<"helixgitpx.common.v1.PageResponse"> & {
  /**
   * @generated from field: string next_page_token = 1;
   */
  nextPageToken: string;

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;
};

/**
 * Describes the message helixgitpx.common.v1.PageResponse.
 * Use `create(PageResponseSchema)` to create a new message.
 */
export const PageResponseSchema: GenMessage<PageResponse> = /*@__PURE__*/
  messageDesc(file_helixgitpx_common_v1_pagination, 1);

