// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/common/v1/time.proto (package helixgitpx.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/common/v1/time.proto.
 */
export const file_helixgitpx_common_v1_time: GenFile = /*@__PURE__*/
  fileDesc("Ch9oZWxpeGdpdHB4L2NvbW1vbi92MS90aW1lLnByb3RvEhRoZWxpeGdpdHB4LmNvbW1vbi52MSJdCglUaW1lUmFuZ2USKAoEZnJvbRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASJgoCdG8YAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQt4BChhjb20uaGVsaXhnaXRweC5jb21tb24udjFCCVRpbWVQcm90b1ABWkVnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC9jb21tb24vdjE7Y29tbW9udjGiAgNIQ1iqAhRIZWxpeGdpdHB4LkNvbW1vbi5WMcoCFEhlbGl4Z2l0cHhcQ29tbW9uXFYx4gIgSGVsaXhnaXRweFxDb21tb25cVjFcR1BCTWV0YWRhdGHqAhZIZWxpeGdpdHB4OjpDb21tb246OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message helixgitpx.common.v1.TimeRange
 */
export type TimeRange = Message<"helixgitpx.common.v1.TimeRange"> & {
  /**
   * @generated from field: google.protobuf.Timestamp from = 1;
   */
  from?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp to = 2;
   */
  to?: Timestamp;
};

/**
 * Describes the message helixgitpx.common.v1.TimeRange.
 * Use `create(TimeRangeSchema)` to create a new message.
 */
export const TimeRangeSchema: GenMessage<TimeRange> = /*@__PURE__*/
  messageDesc(file_helixgitpx_common_v1_time, 0);

