apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../staging

commonLabels:
  helixgitpx.dev/env: prod-eu
  helixgitpx.dev/region: eu-west-1

patches:
  - target: { kind: Application }
    patch: |-
      - op: replace
        path: /spec/source/helm/parameters
        value:
          - name: global.env
            value: prod-eu
