// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/platform/v1/stubs.proto (package helixgitpx.platform.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/platform/v1/stubs.proto.
 */
export const file_helixgitpx_platform_v1_stubs: GenFile = /*@__PURE__*/
  fileDesc("CiJoZWxpeGdpdHB4L3BsYXRmb3JtL3YxL3N0dWJzLnByb3RvEhZoZWxpeGdpdHB4LnBsYXRmb3JtLnYxIh8KC1BsYWNlaG9sZGVyEhAKCHJlc2VydmVkGAEgASgJQu0BChpjb20uaGVsaXhnaXRweC5wbGF0Zm9ybS52MUIKU3R1YnNQcm90b1ABWklnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC9wbGF0Zm9ybS92MTtwbGF0Zm9ybXYxogIDSFBYqgIWSGVsaXhnaXRweC5QbGF0Zm9ybS5WMcoCFkhlbGl4Z2l0cHhcUGxhdGZvcm1cVjHiAiJIZWxpeGdpdHB4XFBsYXRmb3JtXFYxXEdQQk1ldGFkYXRh6gIYSGVsaXhnaXRweDo6UGxhdGZvcm06OlYxYgZwcm90bzM");

/**
 * Stub placeholder — real messages and services land in the milestone owning this domain.
 * See proto/README.md for the M1 → Mx ownership table.
 *
 * @generated from message helixgitpx.platform.v1.Placeholder
 */
export type Placeholder = Message<"helixgitpx.platform.v1.Placeholder"> & {
  /**
   * @generated from field: string reserved = 1;
   */
  reserved: string;
};

/**
 * Describes the message helixgitpx.platform.v1.Placeholder.
 * Use `create(PlaceholderSchema)` to create a new message.
 */
export const PlaceholderSchema: GenMessage<Placeholder> = /*@__PURE__*/
  messageDesc(file_helixgitpx_platform_v1_stubs, 0);

