import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  default: [
    "intro",
    { type: "category", label: "Core",            items: [{ type: "autogenerated", dirName: "00-core" }] },
    { type: "category", label: "Architecture",    items: [{ type: "autogenerated", dirName: "01-architecture" }] },
    { type: "category", label: "Services",        items: [{ type: "autogenerated", dirName: "02-services" }] },
    { type: "category", label: "Data",            items: [{ type: "autogenerated", dirName: "03-data" }] },
    { type: "category", label: "APIs",            items: [{ type: "autogenerated", dirName: "04-apis" }] },
    { type: "category", label: "Frontend",        items: [{ type: "autogenerated", dirName: "05-frontend" }] },
    { type: "category", label: "Mobile",          items: [{ type: "autogenerated", dirName: "06-mobile" }] },
    { type: "category", label: "AI",              items: [{ type: "autogenerated", dirName: "07-ai" }] },
    { type: "category", label: "Security",        items: [{ type: "autogenerated", dirName: "08-security" }] },
    { type: "category", label: "Observability",   items: [{ type: "autogenerated", dirName: "09-observability" }] },
    { type: "category", label: "Testing",         items: [{ type: "autogenerated", dirName: "10-testing" }] },
    { type: "category", label: "DevOps",          items: [{ type: "autogenerated", dirName: "11-devops" }] },
    { type: "category", label: "Operations",      items: [{ type: "autogenerated", dirName: "12-operations" }] },
    { type: "category", label: "Roadmap",         items: [{ type: "autogenerated", dirName: "13-roadmap" }] },
    { type: "category", label: "Diagrams",        items: [{ type: "autogenerated", dirName: "14-diagrams" }] },
    { type: "category", label: "Reference",       items: [{ type: "autogenerated", dirName: "15-reference" }] },
  ],
};
export default sidebars;
