kafka:
  replicas: 1
  storage:
    size: 10Gi
topics:
  - name: hello.said
    partitions: 3
    replicas: 1
    retentionMs: 604800000
  - name: hello.outbox
    partitions: 3
    replicas: 1
    retentionMs: 2592000000
  - name: audit.events
    partitions: 3
    replicas: 1
    retentionMs: -1
  - name: repo.events
    partitions: 3
    replicas: 1
    retentionMs: 604800000
  - name: upstream.webhooks
    partitions: 3
    replicas: 1
    retentionMs: 604800000
