// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/events/v1/events.proto (package helixgitpx.events.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.events.v1.EventType
 */
export enum EventType {
  /**
   * @generated from enum value: EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EVENT_TYPE_REPO_PUSHED = 1;
   */
  REPO_PUSHED = 1,

  /**
   * @generated from enum value: EVENT_TYPE_PR_OPENED = 2;
   */
  PR_OPENED = 2,

  /**
   * @generated from enum value: EVENT_TYPE_PR_MERGED = 3;
   */
  PR_MERGED = 3,

  /**
   * @generated from enum value: EVENT_TYPE_ISSUE_OPENED = 4;
   */
  ISSUE_OPENED = 4,

  /**
   * @generated from enum value: EVENT_TYPE_CONFLICT_DETECTED = 5;
   */
  CONFLICT_DETECTED = 5,

  /**
   * @generated from enum value: EVENT_TYPE_SYNC_COMPLETED = 6;
   */
  SYNC_COMPLETED = 6,

  /**
   * @generated from enum value: EVENT_TYPE_SYNC_FAILED = 7;
   */
  SYNC_FAILED = 7,

  /**
   * @generated from enum value: EVENT_TYPE_POLICY_VIOLATION = 8;
   */
  POLICY_VIOLATION = 8,

  /**
   * @generated from enum value: EVENT_TYPE_AI_DECISION = 9;
   */
  AI_DECISION = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(EventType)
proto3.util.setEnumType(EventType, "helixgitpx.events.v1.EventType", [
  { no: 0, name: "EVENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "EVENT_TYPE_REPO_PUSHED" },
  { no: 2, name: "EVENT_TYPE_PR_OPENED" },
  { no: 3, name: "EVENT_TYPE_PR_MERGED" },
  { no: 4, name: "EVENT_TYPE_ISSUE_OPENED" },
  { no: 5, name: "EVENT_TYPE_CONFLICT_DETECTED" },
  { no: 6, name: "EVENT_TYPE_SYNC_COMPLETED" },
  { no: 7, name: "EVENT_TYPE_SYNC_FAILED" },
  { no: 8, name: "EVENT_TYPE_POLICY_VIOLATION" },
  { no: 9, name: "EVENT_TYPE_AI_DECISION" },
]);

/**
 * @generated from message helixgitpx.events.v1.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: helixgitpx.events.v1.EventType type = 2;
   */
  type = EventType.UNSPECIFIED;

  /**
   * @generated from field: string org_id = 3;
   */
  orgId = "";

  /**
   * @generated from field: string repo_id = 4;
   */
  repoId = "";

  /**
   * @generated from field: string actor_id = 5;
   */
  actorId = "";

  /**
   * @generated from field: google.protobuf.Timestamp at = 6;
   */
  at?: Timestamp;

  /**
   * @generated from field: google.protobuf.Any payload = 7;
   */
  payload?: Any;

  /**
   * @generated from field: string resume_token = 8;
   */
  resumeToken = "";

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.events.v1.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "enum", T: proto3.getEnumType(EventType) },
    { no: 3, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "at", kind: "message", T: Timestamp },
    { no: 7, name: "payload", kind: "message", T: Any },
    { no: 8, name: "resume_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

/**
 * @generated from message helixgitpx.events.v1.SubscribeRequest
 */
export class SubscribeRequest extends Message<SubscribeRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  /**
   * @generated from field: repeated string repo_ids = 2;
   */
  repoIds: string[] = [];

  /**
   * @generated from field: repeated helixgitpx.events.v1.EventType types = 3;
   */
  types: EventType[] = [];

  constructor(data?: PartialMessage<SubscribeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.events.v1.SubscribeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "types", kind: "enum", T: proto3.getEnumType(EventType), repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeRequest {
    return new SubscribeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeRequest {
    return new SubscribeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeRequest {
    return new SubscribeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribeRequest | PlainMessage<SubscribeRequest> | undefined, b: SubscribeRequest | PlainMessage<SubscribeRequest> | undefined): boolean {
    return proto3.util.equals(SubscribeRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.events.v1.ResumeRequest
 */
export class ResumeRequest extends Message<ResumeRequest> {
  /**
   * @generated from field: string resume_token = 1;
   */
  resumeToken = "";

  /**
   * @generated from field: repeated string repo_ids = 2;
   */
  repoIds: string[] = [];

  constructor(data?: PartialMessage<ResumeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.events.v1.ResumeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resume_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResumeRequest {
    return new ResumeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResumeRequest {
    return new ResumeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResumeRequest {
    return new ResumeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ResumeRequest | PlainMessage<ResumeRequest> | undefined, b: ResumeRequest | PlainMessage<ResumeRequest> | undefined): boolean {
    return proto3.util.equals(ResumeRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.events.v1.PublishRequest
 */
export class PublishRequest extends Message<PublishRequest> {
  /**
   * @generated from field: helixgitpx.events.v1.Event event = 1;
   */
  event?: Event;

  constructor(data?: PartialMessage<PublishRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.events.v1.PublishRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event", kind: "message", T: Event },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishRequest {
    return new PublishRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishRequest {
    return new PublishRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishRequest {
    return new PublishRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PublishRequest | PlainMessage<PublishRequest> | undefined, b: PublishRequest | PlainMessage<PublishRequest> | undefined): boolean {
    return proto3.util.equals(PublishRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.events.v1.PublishResponse
 */
export class PublishResponse extends Message<PublishResponse> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  constructor(data?: PartialMessage<PublishResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.events.v1.PublishResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishResponse {
    return new PublishResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishResponse {
    return new PublishResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishResponse {
    return new PublishResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PublishResponse | PlainMessage<PublishResponse> | undefined, b: PublishResponse | PlainMessage<PublishResponse> | undefined): boolean {
    return proto3.util.equals(PublishResponse, a, b);
  }
}

