// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/events/v1/events.proto (package helixgitpx.events.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Event, PublishRequest, PublishResponse, ResumeRequest, SubscribeRequest } from "./events_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * LiveEventsService streams per-org, per-repo events to clients. Backed by
 * Kafka consumer groups; falls back to WebSocket or SSE when gRPC streaming
 * is unavailable.
 *
 * @generated from service helixgitpx.events.v1.LiveEventsService
 */
export const LiveEventsService = {
  typeName: "helixgitpx.events.v1.LiveEventsService",
  methods: {
    /**
     * @generated from rpc helixgitpx.events.v1.LiveEventsService.Subscribe
     */
    subscribe: {
      name: "Subscribe",
      I: SubscribeRequest,
      O: Event,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc helixgitpx.events.v1.LiveEventsService.Resume
     */
    resume: {
      name: "Resume",
      I: ResumeRequest,
      O: Event,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc helixgitpx.events.v1.LiveEventsService.Publish
     */
    publish: {
      name: "Publish",
      I: PublishRequest,
      O: PublishResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

