// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/events/v1/stubs.proto (package helixgitpx.events.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/events/v1/stubs.proto.
 */
export const file_helixgitpx_events_v1_stubs: GenFile = /*@__PURE__*/
  fileDesc("CiBoZWxpeGdpdHB4L2V2ZW50cy92MS9zdHVicy5wcm90bxIUaGVsaXhnaXRweC5ldmVudHMudjEiHwoLUGxhY2Vob2xkZXISEAoIcmVzZXJ2ZWQYASABKAlC3wEKGGNvbS5oZWxpeGdpdHB4LmV2ZW50cy52MUIKU3R1YnNQcm90b1ABWkVnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC9ldmVudHMvdjE7ZXZlbnRzdjGiAgNIRViqAhRIZWxpeGdpdHB4LkV2ZW50cy5WMcoCFEhlbGl4Z2l0cHhcRXZlbnRzXFYx4gIgSGVsaXhnaXRweFxFdmVudHNcVjFcR1BCTWV0YWRhdGHqAhZIZWxpeGdpdHB4OjpFdmVudHM6OlYxYgZwcm90bzM");

/**
 * Stub placeholder — real messages and services land in the milestone owning this domain.
 * See proto/README.md for the M1 → Mx ownership table.
 *
 * @generated from message helixgitpx.events.v1.Placeholder
 */
export type Placeholder = Message<"helixgitpx.events.v1.Placeholder"> & {
  /**
   * @generated from field: string reserved = 1;
   */
  reserved: string;
};

/**
 * Describes the message helixgitpx.events.v1.Placeholder.
 * Use `create(PlaceholderSchema)` to create a new message.
 */
export const PlaceholderSchema: GenMessage<Placeholder> = /*@__PURE__*/
  messageDesc(file_helixgitpx_events_v1_stubs, 0);

