// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/events/v1/stubs.proto (package helixgitpx.events.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Stub placeholder — real messages and services land in the milestone owning this domain.
 * See proto/README.md for the M1 → Mx ownership table.
 *
 * @generated from message helixgitpx.events.v1.Placeholder
 */
export class Placeholder extends Message<Placeholder> {
  /**
   * @generated from field: string reserved = 1;
   */
  reserved = "";

  constructor(data?: PartialMessage<Placeholder>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.events.v1.Placeholder";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reserved", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Placeholder {
    return new Placeholder().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Placeholder {
    return new Placeholder().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Placeholder {
    return new Placeholder().fromJsonString(jsonString, options);
  }

  static equals(a: Placeholder | PlainMessage<Placeholder> | undefined, b: Placeholder | PlainMessage<Placeholder> | undefined): boolean {
    return proto3.util.equals(Placeholder, a, b);
  }
}

