apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata: { name: pod-evict, namespace: helixgitpx }
spec:
  engineState: active
  chaosServiceAccount: litmus-admin
  appinfo: { appns: helixgitpx, applabel: "app.kubernetes.io/part-of=helixgitpx", appkind: deployment }
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - { name: TOTAL_CHAOS_DURATION, value: "120" }
            - { name: CHAOS_INTERVAL, value: "20" }
            - { name: PODS_AFFECTED_PERC, value: "30" }
            - { name: FORCE, value: "true" }
