// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/sync/v1/sync.proto (package helixgitpx.sync.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelJobRequest, GetJobRequest, ListDLQRequest, ListDLQResponse, ListJobsRequest, ListJobsResponse, RequeueFromDLQRequest, RetryJobRequest, SyncJob } from "./sync_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * SyncService exposes the fan-out + inbound-reconcile state managed by
 * sync-orchestrator (Temporal-backed workflows).
 *
 * @generated from service helixgitpx.sync.v1.SyncService
 */
export const SyncService = {
  typeName: "helixgitpx.sync.v1.SyncService",
  methods: {
    /**
     * @generated from rpc helixgitpx.sync.v1.SyncService.ListJobs
     */
    listJobs: {
      name: "ListJobs",
      I: ListJobsRequest,
      O: ListJobsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.sync.v1.SyncService.GetJob
     */
    getJob: {
      name: "GetJob",
      I: GetJobRequest,
      O: SyncJob,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.sync.v1.SyncService.RetryJob
     */
    retryJob: {
      name: "RetryJob",
      I: RetryJobRequest,
      O: SyncJob,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.sync.v1.SyncService.CancelJob
     */
    cancelJob: {
      name: "CancelJob",
      I: CancelJobRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.sync.v1.SyncService.ListDLQ
     */
    listDLQ: {
      name: "ListDLQ",
      I: ListDLQRequest,
      O: ListDLQResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.sync.v1.SyncService.RequeueFromDLQ
     */
    requeueFromDLQ: {
      name: "RequeueFromDLQ",
      I: RequeueFromDLQRequest,
      O: SyncJob,
      kind: MethodKind.Unary,
    },
  }
} as const;

