// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/sync/v1/sync.proto (package helixgitpx.sync.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.sync.v1.JobKind
 */
export enum JobKind {
  /**
   * @generated from enum value: JOB_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: JOB_KIND_FANOUT_PUSH = 1;
   */
  FANOUT_PUSH = 1,

  /**
   * @generated from enum value: JOB_KIND_INBOUND_RECONCILE = 2;
   */
  INBOUND_RECONCILE = 2,

  /**
   * @generated from enum value: JOB_KIND_METADATA_SYNC = 3;
   */
  METADATA_SYNC = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(JobKind)
proto3.util.setEnumType(JobKind, "helixgitpx.sync.v1.JobKind", [
  { no: 0, name: "JOB_KIND_UNSPECIFIED" },
  { no: 1, name: "JOB_KIND_FANOUT_PUSH" },
  { no: 2, name: "JOB_KIND_INBOUND_RECONCILE" },
  { no: 3, name: "JOB_KIND_METADATA_SYNC" },
]);

/**
 * @generated from enum helixgitpx.sync.v1.JobStatus
 */
export enum JobStatus {
  /**
   * @generated from enum value: JOB_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: JOB_STATUS_QUEUED = 1;
   */
  QUEUED = 1,

  /**
   * @generated from enum value: JOB_STATUS_RUNNING = 2;
   */
  RUNNING = 2,

  /**
   * @generated from enum value: JOB_STATUS_SUCCEEDED = 3;
   */
  SUCCEEDED = 3,

  /**
   * @generated from enum value: JOB_STATUS_FAILED = 4;
   */
  FAILED = 4,

  /**
   * @generated from enum value: JOB_STATUS_DLQ = 5;
   */
  DLQ = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(JobStatus)
proto3.util.setEnumType(JobStatus, "helixgitpx.sync.v1.JobStatus", [
  { no: 0, name: "JOB_STATUS_UNSPECIFIED" },
  { no: 1, name: "JOB_STATUS_QUEUED" },
  { no: 2, name: "JOB_STATUS_RUNNING" },
  { no: 3, name: "JOB_STATUS_SUCCEEDED" },
  { no: 4, name: "JOB_STATUS_FAILED" },
  { no: 5, name: "JOB_STATUS_DLQ" },
]);

/**
 * @generated from message helixgitpx.sync.v1.SyncJob
 */
export class SyncJob extends Message<SyncJob> {
  /**
   * Temporal workflow ID
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string repo_id = 2;
   */
  repoId = "";

  /**
   * @generated from field: helixgitpx.sync.v1.JobKind kind = 3;
   */
  kind = JobKind.UNSPECIFIED;

  /**
   * @generated from field: helixgitpx.sync.v1.JobStatus status = 4;
   */
  status = JobStatus.UNSPECIFIED;

  /**
   * e.g. "github"
   *
   * @generated from field: string upstream = 5;
   */
  upstream = "";

  /**
   * e.g. "refs/heads/main"
   *
   * @generated from field: string ref = 6;
   */
  ref = "";

  /**
   * @generated from field: int32 attempt = 7;
   */
  attempt = 0;

  /**
   * @generated from field: string last_error = 8;
   */
  lastError = "";

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 9;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp finished_at = 10;
   */
  finishedAt?: Timestamp;

  constructor(data?: PartialMessage<SyncJob>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.SyncJob";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "kind", kind: "enum", T: proto3.getEnumType(JobKind) },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(JobStatus) },
    { no: 5, name: "upstream", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "attempt", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "last_error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "started_at", kind: "message", T: Timestamp },
    { no: 10, name: "finished_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SyncJob {
    return new SyncJob().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SyncJob {
    return new SyncJob().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SyncJob {
    return new SyncJob().fromJsonString(jsonString, options);
  }

  static equals(a: SyncJob | PlainMessage<SyncJob> | undefined, b: SyncJob | PlainMessage<SyncJob> | undefined): boolean {
    return proto3.util.equals(SyncJob, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.ListJobsRequest
 */
export class ListJobsRequest extends Message<ListJobsRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: helixgitpx.sync.v1.JobStatus status = 2;
   */
  status = JobStatus.UNSPECIFIED;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 4;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListJobsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.ListJobsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(JobStatus) },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListJobsRequest {
    return new ListJobsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListJobsRequest {
    return new ListJobsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListJobsRequest {
    return new ListJobsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListJobsRequest | PlainMessage<ListJobsRequest> | undefined, b: ListJobsRequest | PlainMessage<ListJobsRequest> | undefined): boolean {
    return proto3.util.equals(ListJobsRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.ListJobsResponse
 */
export class ListJobsResponse extends Message<ListJobsResponse> {
  /**
   * @generated from field: repeated helixgitpx.sync.v1.SyncJob jobs = 1;
   */
  jobs: SyncJob[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListJobsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.ListJobsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "jobs", kind: "message", T: SyncJob, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListJobsResponse {
    return new ListJobsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListJobsResponse {
    return new ListJobsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListJobsResponse {
    return new ListJobsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListJobsResponse | PlainMessage<ListJobsResponse> | undefined, b: ListJobsResponse | PlainMessage<ListJobsResponse> | undefined): boolean {
    return proto3.util.equals(ListJobsResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.GetJobRequest
 */
export class GetJobRequest extends Message<GetJobRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetJobRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.GetJobRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetJobRequest {
    return new GetJobRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetJobRequest {
    return new GetJobRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetJobRequest {
    return new GetJobRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetJobRequest | PlainMessage<GetJobRequest> | undefined, b: GetJobRequest | PlainMessage<GetJobRequest> | undefined): boolean {
    return proto3.util.equals(GetJobRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.RetryJobRequest
 */
export class RetryJobRequest extends Message<RetryJobRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<RetryJobRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.RetryJobRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RetryJobRequest {
    return new RetryJobRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RetryJobRequest {
    return new RetryJobRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RetryJobRequest {
    return new RetryJobRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RetryJobRequest | PlainMessage<RetryJobRequest> | undefined, b: RetryJobRequest | PlainMessage<RetryJobRequest> | undefined): boolean {
    return proto3.util.equals(RetryJobRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.CancelJobRequest
 */
export class CancelJobRequest extends Message<CancelJobRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<CancelJobRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.CancelJobRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelJobRequest {
    return new CancelJobRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelJobRequest {
    return new CancelJobRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelJobRequest {
    return new CancelJobRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelJobRequest | PlainMessage<CancelJobRequest> | undefined, b: CancelJobRequest | PlainMessage<CancelJobRequest> | undefined): boolean {
    return proto3.util.equals(CancelJobRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.ListDLQRequest
 */
export class ListDLQRequest extends Message<ListDLQRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListDLQRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.ListDLQRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDLQRequest {
    return new ListDLQRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDLQRequest {
    return new ListDLQRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDLQRequest {
    return new ListDLQRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListDLQRequest | PlainMessage<ListDLQRequest> | undefined, b: ListDLQRequest | PlainMessage<ListDLQRequest> | undefined): boolean {
    return proto3.util.equals(ListDLQRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.ListDLQResponse
 */
export class ListDLQResponse extends Message<ListDLQResponse> {
  /**
   * @generated from field: repeated helixgitpx.sync.v1.SyncJob jobs = 1;
   */
  jobs: SyncJob[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListDLQResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.ListDLQResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "jobs", kind: "message", T: SyncJob, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDLQResponse {
    return new ListDLQResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDLQResponse {
    return new ListDLQResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDLQResponse {
    return new ListDLQResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListDLQResponse | PlainMessage<ListDLQResponse> | undefined, b: ListDLQResponse | PlainMessage<ListDLQResponse> | undefined): boolean {
    return proto3.util.equals(ListDLQResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.sync.v1.RequeueFromDLQRequest
 */
export class RequeueFromDLQRequest extends Message<RequeueFromDLQRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<RequeueFromDLQRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.sync.v1.RequeueFromDLQRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequeueFromDLQRequest {
    return new RequeueFromDLQRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequeueFromDLQRequest {
    return new RequeueFromDLQRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequeueFromDLQRequest {
    return new RequeueFromDLQRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RequeueFromDLQRequest | PlainMessage<RequeueFromDLQRequest> | undefined, b: RequeueFromDLQRequest | PlainMessage<RequeueFromDLQRequest> | undefined): boolean {
    return proto3.util.equals(RequeueFromDLQRequest, a, b);
  }
}

