// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/ai/v1/ai.proto (package helixgitpx.ai.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatMessage, ChatRequest, ConflictProposal, FeedbackRequest, ProposeConflictResolutionRequest, SuggestLabelRequest, SuggestLabelResponse, SummarizeRequest, SummarizeResponse } from "./ai_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helixgitpx.ai.v1.AIService
 */
export const AIService = {
  typeName: "helixgitpx.ai.v1.AIService",
  methods: {
    /**
     * @generated from rpc helixgitpx.ai.v1.AIService.Summarize
     */
    summarize: {
      name: "Summarize",
      I: SummarizeRequest,
      O: SummarizeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.ai.v1.AIService.ProposeConflictResolution
     */
    proposeConflictResolution: {
      name: "ProposeConflictResolution",
      I: ProposeConflictResolutionRequest,
      O: ConflictProposal,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.ai.v1.AIService.SuggestLabel
     */
    suggestLabel: {
      name: "SuggestLabel",
      I: SuggestLabelRequest,
      O: SuggestLabelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.ai.v1.AIService.Chat
     */
    chat: {
      name: "Chat",
      I: ChatRequest,
      O: ChatMessage,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc helixgitpx.ai.v1.AIService.Feedback
     */
    feedback: {
      name: "Feedback",
      I: FeedbackRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

