// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/ai/v1/ai.proto (package helixgitpx.ai.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message helixgitpx.ai.v1.SummarizeRequest
 */
export class SummarizeRequest extends Message<SummarizeRequest> {
  /**
   * "pr" | "issue" | "commit"
   *
   * @generated from field: string target_kind = 1;
   */
  targetKind = "";

  /**
   * @generated from field: string target_id = 2;
   */
  targetId = "";

  /**
   * @generated from field: string content = 3;
   */
  content = "";

  /**
   * @generated from field: int32 max_words = 4;
   */
  maxWords = 0;

  constructor(data?: PartialMessage<SummarizeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.SummarizeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "target_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "max_words", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SummarizeRequest {
    return new SummarizeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SummarizeRequest {
    return new SummarizeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SummarizeRequest {
    return new SummarizeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SummarizeRequest | PlainMessage<SummarizeRequest> | undefined, b: SummarizeRequest | PlainMessage<SummarizeRequest> | undefined): boolean {
    return proto3.util.equals(SummarizeRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.SummarizeResponse
 */
export class SummarizeResponse extends Message<SummarizeResponse> {
  /**
   * @generated from field: string summary = 1;
   */
  summary = "";

  /**
   * @generated from field: string model = 2;
   */
  model = "";

  /**
   * @generated from field: double confidence = 3;
   */
  confidence = 0;

  constructor(data?: PartialMessage<SummarizeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.SummarizeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "summary", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "confidence", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SummarizeResponse {
    return new SummarizeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SummarizeResponse {
    return new SummarizeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SummarizeResponse {
    return new SummarizeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SummarizeResponse | PlainMessage<SummarizeResponse> | undefined, b: SummarizeResponse | PlainMessage<SummarizeResponse> | undefined): boolean {
    return proto3.util.equals(SummarizeResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.ProposeConflictResolutionRequest
 */
export class ProposeConflictResolutionRequest extends Message<ProposeConflictResolutionRequest> {
  /**
   * @generated from field: string conflict_id = 1;
   */
  conflictId = "";

  /**
   * @generated from field: bytes context = 2;
   */
  context = new Uint8Array(0);

  constructor(data?: PartialMessage<ProposeConflictResolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.ProposeConflictResolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conflict_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "context", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProposeConflictResolutionRequest {
    return new ProposeConflictResolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProposeConflictResolutionRequest {
    return new ProposeConflictResolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProposeConflictResolutionRequest {
    return new ProposeConflictResolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ProposeConflictResolutionRequest | PlainMessage<ProposeConflictResolutionRequest> | undefined, b: ProposeConflictResolutionRequest | PlainMessage<ProposeConflictResolutionRequest> | undefined): boolean {
    return proto3.util.equals(ProposeConflictResolutionRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.ConflictProposal
 */
export class ConflictProposal extends Message<ConflictProposal> {
  /**
   * @generated from field: string conflict_id = 1;
   */
  conflictId = "";

  /**
   * @generated from field: string rationale = 2;
   */
  rationale = "";

  /**
   * @generated from field: bytes patch = 3;
   */
  patch = new Uint8Array(0);

  /**
   * @generated from field: double confidence = 4;
   */
  confidence = 0;

  /**
   * @generated from field: string model = 5;
   */
  model = "";

  constructor(data?: PartialMessage<ConflictProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.ConflictProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conflict_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "rationale", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "patch", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "confidence", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConflictProposal {
    return new ConflictProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConflictProposal {
    return new ConflictProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConflictProposal {
    return new ConflictProposal().fromJsonString(jsonString, options);
  }

  static equals(a: ConflictProposal | PlainMessage<ConflictProposal> | undefined, b: ConflictProposal | PlainMessage<ConflictProposal> | undefined): boolean {
    return proto3.util.equals(ConflictProposal, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.SuggestLabelRequest
 */
export class SuggestLabelRequest extends Message<SuggestLabelRequest> {
  /**
   * @generated from field: string target_kind = 1;
   */
  targetKind = "";

  /**
   * @generated from field: string target_id = 2;
   */
  targetId = "";

  /**
   * @generated from field: string content = 3;
   */
  content = "";

  /**
   * @generated from field: repeated string available_labels = 4;
   */
  availableLabels: string[] = [];

  constructor(data?: PartialMessage<SuggestLabelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.SuggestLabelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "target_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "available_labels", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SuggestLabelRequest {
    return new SuggestLabelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SuggestLabelRequest {
    return new SuggestLabelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SuggestLabelRequest {
    return new SuggestLabelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SuggestLabelRequest | PlainMessage<SuggestLabelRequest> | undefined, b: SuggestLabelRequest | PlainMessage<SuggestLabelRequest> | undefined): boolean {
    return proto3.util.equals(SuggestLabelRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.SuggestLabelResponse
 */
export class SuggestLabelResponse extends Message<SuggestLabelResponse> {
  /**
   * @generated from field: repeated string labels = 1;
   */
  labels: string[] = [];

  /**
   * @generated from field: string model = 2;
   */
  model = "";

  constructor(data?: PartialMessage<SuggestLabelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.SuggestLabelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "labels", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SuggestLabelResponse {
    return new SuggestLabelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SuggestLabelResponse {
    return new SuggestLabelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SuggestLabelResponse {
    return new SuggestLabelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SuggestLabelResponse | PlainMessage<SuggestLabelResponse> | undefined, b: SuggestLabelResponse | PlainMessage<SuggestLabelResponse> | undefined): boolean {
    return proto3.util.equals(SuggestLabelResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.ChatRequest
 */
export class ChatRequest extends Message<ChatRequest> {
  /**
   * @generated from field: string conversation_id = 1;
   */
  conversationId = "";

  /**
   * @generated from field: string actor_id = 2;
   */
  actorId = "";

  /**
   * @generated from field: repeated helixgitpx.ai.v1.ChatMessage messages = 3;
   */
  messages: ChatMessage[] = [];

  constructor(data?: PartialMessage<ChatRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.ChatRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "messages", kind: "message", T: ChatMessage, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChatRequest {
    return new ChatRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChatRequest {
    return new ChatRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChatRequest {
    return new ChatRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ChatRequest | PlainMessage<ChatRequest> | undefined, b: ChatRequest | PlainMessage<ChatRequest> | undefined): boolean {
    return proto3.util.equals(ChatRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.ChatMessage
 */
export class ChatMessage extends Message<ChatMessage> {
  /**
   * "user" | "assistant" | "system"
   *
   * @generated from field: string role = 1;
   */
  role = "";

  /**
   * @generated from field: string content = 2;
   */
  content = "";

  /**
   * @generated from field: google.protobuf.Timestamp at = 3;
   */
  at?: Timestamp;

  constructor(data?: PartialMessage<ChatMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.ChatMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChatMessage {
    return new ChatMessage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChatMessage {
    return new ChatMessage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChatMessage {
    return new ChatMessage().fromJsonString(jsonString, options);
  }

  static equals(a: ChatMessage | PlainMessage<ChatMessage> | undefined, b: ChatMessage | PlainMessage<ChatMessage> | undefined): boolean {
    return proto3.util.equals(ChatMessage, a, b);
  }
}

/**
 * @generated from message helixgitpx.ai.v1.FeedbackRequest
 */
export class FeedbackRequest extends Message<FeedbackRequest> {
  /**
   * @generated from field: string decision_id = 1;
   */
  decisionId = "";

  /**
   * "accept" | "reject" | "edit"
   *
   * @generated from field: string verdict = 2;
   */
  verdict = "";

  /**
   * @generated from field: string actor_id = 3;
   */
  actorId = "";

  /**
   * @generated from field: string notes = 4;
   */
  notes = "";

  constructor(data?: PartialMessage<FeedbackRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.ai.v1.FeedbackRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "decision_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "verdict", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FeedbackRequest {
    return new FeedbackRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FeedbackRequest {
    return new FeedbackRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FeedbackRequest {
    return new FeedbackRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FeedbackRequest | PlainMessage<FeedbackRequest> | undefined, b: FeedbackRequest | PlainMessage<FeedbackRequest> | undefined): boolean {
    return proto3.util.equals(FeedbackRequest, a, b);
  }
}

