// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/upstream/v1/stubs.proto (package helixgitpx.upstream.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/upstream/v1/stubs.proto.
 */
export const file_helixgitpx_upstream_v1_stubs: GenFile = /*@__PURE__*/
  fileDesc("CiJoZWxpeGdpdHB4L3Vwc3RyZWFtL3YxL3N0dWJzLnByb3RvEhZoZWxpeGdpdHB4LnVwc3RyZWFtLnYxIh8KC1BsYWNlaG9sZGVyEhAKCHJlc2VydmVkGAEgASgJQu0BChpjb20uaGVsaXhnaXRweC51cHN0cmVhbS52MUIKU3R1YnNQcm90b1ABWklnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC91cHN0cmVhbS92MTt1cHN0cmVhbXYxogIDSFVYqgIWSGVsaXhnaXRweC5VcHN0cmVhbS5WMcoCFkhlbGl4Z2l0cHhcVXBzdHJlYW1cVjHiAiJIZWxpeGdpdHB4XFVwc3RyZWFtXFYxXEdQQk1ldGFkYXRh6gIYSGVsaXhnaXRweDo6VXBzdHJlYW06OlYxYgZwcm90bzM");

/**
 * Stub placeholder — real messages and services land in the milestone owning this domain.
 * See proto/README.md for the M1 → Mx ownership table.
 *
 * @generated from message helixgitpx.upstream.v1.Placeholder
 */
export type Placeholder = Message<"helixgitpx.upstream.v1.Placeholder"> & {
  /**
   * @generated from field: string reserved = 1;
   */
  reserved: string;
};

/**
 * Describes the message helixgitpx.upstream.v1.Placeholder.
 * Use `create(PlaceholderSchema)` to create a new message.
 */
export const PlaceholderSchema: GenMessage<Placeholder> = /*@__PURE__*/
  messageDesc(file_helixgitpx_upstream_v1_stubs, 0);

