// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/upstream/v1/upstream.proto (package helixgitpx.upstream.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Binding, BindRequest, CreateUpstreamRequest, DeleteUpstreamRequest, GetUpstreamRequest, ListBindingsRequest, ListBindingsResponse, ListUpstreamsResponse, UnbindRequest, UpdateUpstreamRequest, Upstream } from "./upstream_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helixgitpx.upstream.v1.UpstreamService
 */
export const UpstreamService = {
  typeName: "helixgitpx.upstream.v1.UpstreamService",
  methods: {
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.Create
     */
    create: {
      name: "Create",
      I: CreateUpstreamRequest,
      O: Upstream,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.Get
     */
    get: {
      name: "Get",
      I: GetUpstreamRequest,
      O: Upstream,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.List
     */
    list: {
      name: "List",
      I: Empty,
      O: ListUpstreamsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.Update
     */
    update: {
      name: "Update",
      I: UpdateUpstreamRequest,
      O: Upstream,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteUpstreamRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.Bind
     */
    bind: {
      name: "Bind",
      I: BindRequest,
      O: Binding,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.Unbind
     */
    unbind: {
      name: "Unbind",
      I: UnbindRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.upstream.v1.UpstreamService.ListBindings
     */
    listBindings: {
      name: "ListBindings",
      I: ListBindingsRequest,
      O: ListBindingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

