// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/upstream/v1/upstream.proto (package helixgitpx.upstream.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum helixgitpx.upstream.v1.Provider
 */
export enum Provider {
  /**
   * @generated from enum value: PROVIDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PROVIDER_GITHUB = 1;
   */
  GITHUB = 1,

  /**
   * @generated from enum value: PROVIDER_GITLAB = 2;
   */
  GITLAB = 2,

  /**
   * @generated from enum value: PROVIDER_GITEA = 3;
   */
  GITEA = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(Provider)
proto3.util.setEnumType(Provider, "helixgitpx.upstream.v1.Provider", [
  { no: 0, name: "PROVIDER_UNSPECIFIED" },
  { no: 1, name: "PROVIDER_GITHUB" },
  { no: 2, name: "PROVIDER_GITLAB" },
  { no: 3, name: "PROVIDER_GITEA" },
]);

/**
 * @generated from enum helixgitpx.upstream.v1.Direction
 */
export enum Direction {
  /**
   * @generated from enum value: DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIRECTION_PUSH = 1;
   */
  PUSH = 1,

  /**
   * @generated from enum value: DIRECTION_FETCH = 2;
   */
  FETCH = 2,

  /**
   * @generated from enum value: DIRECTION_MIRROR = 3;
   */
  MIRROR = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(Direction)
proto3.util.setEnumType(Direction, "helixgitpx.upstream.v1.Direction", [
  { no: 0, name: "DIRECTION_UNSPECIFIED" },
  { no: 1, name: "DIRECTION_PUSH" },
  { no: 2, name: "DIRECTION_FETCH" },
  { no: 3, name: "DIRECTION_MIRROR" },
]);

/**
 * @generated from message helixgitpx.upstream.v1.Upstream
 */
export class Upstream extends Message<Upstream> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string slug = 2;
   */
  slug = "";

  /**
   * @generated from field: helixgitpx.upstream.v1.Provider provider = 3;
   */
  provider = Provider.UNSPECIFIED;

  /**
   * @generated from field: string base_url = 4;
   */
  baseUrl = "";

  /**
   * @generated from field: string vault_path = 5;
   */
  vaultPath = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Upstream>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.Upstream";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "provider", kind: "enum", T: proto3.getEnumType(Provider) },
    { no: 4, name: "base_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "vault_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Upstream {
    return new Upstream().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Upstream {
    return new Upstream().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Upstream {
    return new Upstream().fromJsonString(jsonString, options);
  }

  static equals(a: Upstream | PlainMessage<Upstream> | undefined, b: Upstream | PlainMessage<Upstream> | undefined): boolean {
    return proto3.util.equals(Upstream, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.Binding
 */
export class Binding extends Message<Binding> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: string upstream_id = 2;
   */
  upstreamId = "";

  /**
   * @generated from field: string remote_name = 3;
   */
  remoteName = "";

  /**
   * @generated from field: helixgitpx.upstream.v1.Direction direction = 4;
   */
  direction = Direction.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp last_sync_at = 5;
   */
  lastSyncAt?: Timestamp;

  constructor(data?: PartialMessage<Binding>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.Binding";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "upstream_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "remote_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "direction", kind: "enum", T: proto3.getEnumType(Direction) },
    { no: 5, name: "last_sync_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Binding {
    return new Binding().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Binding {
    return new Binding().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Binding {
    return new Binding().fromJsonString(jsonString, options);
  }

  static equals(a: Binding | PlainMessage<Binding> | undefined, b: Binding | PlainMessage<Binding> | undefined): boolean {
    return proto3.util.equals(Binding, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.CreateUpstreamRequest
 */
export class CreateUpstreamRequest extends Message<CreateUpstreamRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  /**
   * @generated from field: helixgitpx.upstream.v1.Provider provider = 2;
   */
  provider = Provider.UNSPECIFIED;

  /**
   * @generated from field: string base_url = 3;
   */
  baseUrl = "";

  /**
   * @generated from field: string vault_path = 4;
   */
  vaultPath = "";

  constructor(data?: PartialMessage<CreateUpstreamRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.CreateUpstreamRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "provider", kind: "enum", T: proto3.getEnumType(Provider) },
    { no: 3, name: "base_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "vault_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateUpstreamRequest {
    return new CreateUpstreamRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateUpstreamRequest {
    return new CreateUpstreamRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateUpstreamRequest {
    return new CreateUpstreamRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateUpstreamRequest | PlainMessage<CreateUpstreamRequest> | undefined, b: CreateUpstreamRequest | PlainMessage<CreateUpstreamRequest> | undefined): boolean {
    return proto3.util.equals(CreateUpstreamRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.GetUpstreamRequest
 */
export class GetUpstreamRequest extends Message<GetUpstreamRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  constructor(data?: PartialMessage<GetUpstreamRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.GetUpstreamRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUpstreamRequest {
    return new GetUpstreamRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUpstreamRequest {
    return new GetUpstreamRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUpstreamRequest {
    return new GetUpstreamRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUpstreamRequest | PlainMessage<GetUpstreamRequest> | undefined, b: GetUpstreamRequest | PlainMessage<GetUpstreamRequest> | undefined): boolean {
    return proto3.util.equals(GetUpstreamRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.UpdateUpstreamRequest
 */
export class UpdateUpstreamRequest extends Message<UpdateUpstreamRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  /**
   * @generated from field: string base_url = 2;
   */
  baseUrl = "";

  /**
   * @generated from field: string vault_path = 3;
   */
  vaultPath = "";

  constructor(data?: PartialMessage<UpdateUpstreamRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.UpdateUpstreamRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "base_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "vault_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUpstreamRequest {
    return new UpdateUpstreamRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUpstreamRequest {
    return new UpdateUpstreamRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUpstreamRequest {
    return new UpdateUpstreamRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateUpstreamRequest | PlainMessage<UpdateUpstreamRequest> | undefined, b: UpdateUpstreamRequest | PlainMessage<UpdateUpstreamRequest> | undefined): boolean {
    return proto3.util.equals(UpdateUpstreamRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.DeleteUpstreamRequest
 */
export class DeleteUpstreamRequest extends Message<DeleteUpstreamRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  constructor(data?: PartialMessage<DeleteUpstreamRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.DeleteUpstreamRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteUpstreamRequest {
    return new DeleteUpstreamRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteUpstreamRequest {
    return new DeleteUpstreamRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteUpstreamRequest {
    return new DeleteUpstreamRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteUpstreamRequest | PlainMessage<DeleteUpstreamRequest> | undefined, b: DeleteUpstreamRequest | PlainMessage<DeleteUpstreamRequest> | undefined): boolean {
    return proto3.util.equals(DeleteUpstreamRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.ListUpstreamsResponse
 */
export class ListUpstreamsResponse extends Message<ListUpstreamsResponse> {
  /**
   * @generated from field: repeated helixgitpx.upstream.v1.Upstream upstreams = 1;
   */
  upstreams: Upstream[] = [];

  constructor(data?: PartialMessage<ListUpstreamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.ListUpstreamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "upstreams", kind: "message", T: Upstream, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUpstreamsResponse {
    return new ListUpstreamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUpstreamsResponse {
    return new ListUpstreamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUpstreamsResponse {
    return new ListUpstreamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListUpstreamsResponse | PlainMessage<ListUpstreamsResponse> | undefined, b: ListUpstreamsResponse | PlainMessage<ListUpstreamsResponse> | undefined): boolean {
    return proto3.util.equals(ListUpstreamsResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.BindRequest
 */
export class BindRequest extends Message<BindRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: string upstream_id = 2;
   */
  upstreamId = "";

  /**
   * @generated from field: string remote_name = 3;
   */
  remoteName = "";

  /**
   * @generated from field: helixgitpx.upstream.v1.Direction direction = 4;
   */
  direction = Direction.UNSPECIFIED;

  constructor(data?: PartialMessage<BindRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.BindRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "upstream_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "remote_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "direction", kind: "enum", T: proto3.getEnumType(Direction) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BindRequest {
    return new BindRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BindRequest {
    return new BindRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BindRequest {
    return new BindRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BindRequest | PlainMessage<BindRequest> | undefined, b: BindRequest | PlainMessage<BindRequest> | undefined): boolean {
    return proto3.util.equals(BindRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.UnbindRequest
 */
export class UnbindRequest extends Message<UnbindRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: string upstream_id = 2;
   */
  upstreamId = "";

  /**
   * @generated from field: string remote_name = 3;
   */
  remoteName = "";

  constructor(data?: PartialMessage<UnbindRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.UnbindRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "upstream_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "remote_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnbindRequest {
    return new UnbindRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnbindRequest {
    return new UnbindRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnbindRequest {
    return new UnbindRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnbindRequest | PlainMessage<UnbindRequest> | undefined, b: UnbindRequest | PlainMessage<UnbindRequest> | undefined): boolean {
    return proto3.util.equals(UnbindRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.ListBindingsRequest
 */
export class ListBindingsRequest extends Message<ListBindingsRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  constructor(data?: PartialMessage<ListBindingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.ListBindingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBindingsRequest {
    return new ListBindingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBindingsRequest {
    return new ListBindingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBindingsRequest {
    return new ListBindingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListBindingsRequest | PlainMessage<ListBindingsRequest> | undefined, b: ListBindingsRequest | PlainMessage<ListBindingsRequest> | undefined): boolean {
    return proto3.util.equals(ListBindingsRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.upstream.v1.ListBindingsResponse
 */
export class ListBindingsResponse extends Message<ListBindingsResponse> {
  /**
   * @generated from field: repeated helixgitpx.upstream.v1.Binding bindings = 1;
   */
  bindings: Binding[] = [];

  constructor(data?: PartialMessage<ListBindingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.upstream.v1.ListBindingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bindings", kind: "message", T: Binding, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBindingsResponse {
    return new ListBindingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBindingsResponse {
    return new ListBindingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBindingsResponse {
    return new ListBindingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListBindingsResponse | PlainMessage<ListBindingsResponse> | undefined, b: ListBindingsResponse | PlainMessage<ListBindingsResponse> | undefined): boolean {
    return proto3.util.equals(ListBindingsResponse, a, b);
  }
}

