// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/org/v1/org.proto (package helixgitpx.org.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message helixgitpx.org.v1.Org
 */
export class Org extends Message<Org> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string slug = 2;
   */
  slug = "";

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Org>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.org.v1.Org";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Org {
    return new Org().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Org {
    return new Org().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Org {
    return new Org().fromJsonString(jsonString, options);
  }

  static equals(a: Org | PlainMessage<Org> | undefined, b: Org | PlainMessage<Org> | undefined): boolean {
    return proto3.util.equals(Org, a, b);
  }
}

/**
 * @generated from message helixgitpx.org.v1.CreateOrgRequest
 */
export class CreateOrgRequest extends Message<CreateOrgRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  constructor(data?: PartialMessage<CreateOrgRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.org.v1.CreateOrgRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateOrgRequest {
    return new CreateOrgRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateOrgRequest {
    return new CreateOrgRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateOrgRequest {
    return new CreateOrgRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateOrgRequest | PlainMessage<CreateOrgRequest> | undefined, b: CreateOrgRequest | PlainMessage<CreateOrgRequest> | undefined): boolean {
    return proto3.util.equals(CreateOrgRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.org.v1.GetOrgRequest
 */
export class GetOrgRequest extends Message<GetOrgRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  constructor(data?: PartialMessage<GetOrgRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.org.v1.GetOrgRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetOrgRequest {
    return new GetOrgRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetOrgRequest {
    return new GetOrgRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetOrgRequest {
    return new GetOrgRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetOrgRequest | PlainMessage<GetOrgRequest> | undefined, b: GetOrgRequest | PlainMessage<GetOrgRequest> | undefined): boolean {
    return proto3.util.equals(GetOrgRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.org.v1.UpdateOrgRequest
 */
export class UpdateOrgRequest extends Message<UpdateOrgRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  constructor(data?: PartialMessage<UpdateOrgRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.org.v1.UpdateOrgRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateOrgRequest {
    return new UpdateOrgRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateOrgRequest {
    return new UpdateOrgRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateOrgRequest {
    return new UpdateOrgRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateOrgRequest | PlainMessage<UpdateOrgRequest> | undefined, b: UpdateOrgRequest | PlainMessage<UpdateOrgRequest> | undefined): boolean {
    return proto3.util.equals(UpdateOrgRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.org.v1.DeleteOrgRequest
 */
export class DeleteOrgRequest extends Message<DeleteOrgRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  constructor(data?: PartialMessage<DeleteOrgRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.org.v1.DeleteOrgRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteOrgRequest {
    return new DeleteOrgRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteOrgRequest {
    return new DeleteOrgRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteOrgRequest {
    return new DeleteOrgRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteOrgRequest | PlainMessage<DeleteOrgRequest> | undefined, b: DeleteOrgRequest | PlainMessage<DeleteOrgRequest> | undefined): boolean {
    return proto3.util.equals(DeleteOrgRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.org.v1.ListOrgsRequest
 */
export class ListOrgsRequest extends Message<ListOrgsRequest> {
  constructor(data?: PartialMessage<ListOrgsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.org.v1.ListOrgsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListOrgsRequest {
    return new ListOrgsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListOrgsRequest {
    return new ListOrgsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListOrgsRequest {
    return new ListOrgsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListOrgsRequest | PlainMessage<ListOrgsRequest> | undefined, b: ListOrgsRequest | PlainMessage<ListOrgsRequest> | undefined): boolean {
    return proto3.util.equals(ListOrgsRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.org.v1.ListOrgsResponse
 */
export class ListOrgsResponse extends Message<ListOrgsResponse> {
  /**
   * @generated from field: repeated helixgitpx.org.v1.Org orgs = 1;
   */
  orgs: Org[] = [];

  constructor(data?: PartialMessage<ListOrgsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.org.v1.ListOrgsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "orgs", kind: "message", T: Org, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListOrgsResponse {
    return new ListOrgsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListOrgsResponse {
    return new ListOrgsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListOrgsResponse {
    return new ListOrgsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListOrgsResponse | PlainMessage<ListOrgsResponse> | undefined, b: ListOrgsResponse | PlainMessage<ListOrgsResponse> | undefined): boolean {
    return proto3.util.equals(ListOrgsResponse, a, b);
  }
}

