// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/org/v1/org.proto (package helixgitpx.org.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/org/v1/org.proto.
 */
export const file_helixgitpx_org_v1_org: GenFile = /*@__PURE__*/
  fileDesc("ChtoZWxpeGdpdHB4L29yZy92MS9vcmcucHJvdG8SEWhlbGl4Z2l0cHgub3JnLnYxIl0KA09yZxIKCgJpZBgBIAEoCRIMCgRzbHVnGAIgASgJEgwKBG5hbWUYAyABKAkSLgoKY3JlYXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiLgoQQ3JlYXRlT3JnUmVxdWVzdBIMCgRzbHVnGAEgASgJEgwKBG5hbWUYAiABKAkiHQoNR2V0T3JnUmVxdWVzdBIMCgRzbHVnGAEgASgJIi4KEFVwZGF0ZU9yZ1JlcXVlc3QSDAoEc2x1ZxgBIAEoCRIMCgRuYW1lGAIgASgJIiAKEERlbGV0ZU9yZ1JlcXVlc3QSDAoEc2x1ZxgBIAEoCSIRCg9MaXN0T3Jnc1JlcXVlc3QiOAoQTGlzdE9yZ3NSZXNwb25zZRIkCgRvcmdzGAEgAygLMhYuaGVsaXhnaXRweC5vcmcudjEuT3JnMvMCCgpPcmdTZXJ2aWNlEkUKBkNyZWF0ZRIjLmhlbGl4Z2l0cHgub3JnLnYxLkNyZWF0ZU9yZ1JlcXVlc3QaFi5oZWxpeGdpdHB4Lm9yZy52MS5PcmcSPwoDR2V0EiAuaGVsaXhnaXRweC5vcmcudjEuR2V0T3JnUmVxdWVzdBoWLmhlbGl4Z2l0cHgub3JnLnYxLk9yZxJPCgRMaXN0EiIuaGVsaXhnaXRweC5vcmcudjEuTGlzdE9yZ3NSZXF1ZXN0GiMuaGVsaXhnaXRweC5vcmcudjEuTGlzdE9yZ3NSZXNwb25zZRJFCgZVcGRhdGUSIy5oZWxpeGdpdHB4Lm9yZy52MS5VcGRhdGVPcmdSZXF1ZXN0GhYuaGVsaXhnaXRweC5vcmcudjEuT3JnEkUKBkRlbGV0ZRIjLmhlbGl4Z2l0cHgub3JnLnYxLkRlbGV0ZU9yZ1JlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHlCyAEKFWNvbS5oZWxpeGdpdHB4Lm9yZy52MUIIT3JnUHJvdG9QAVo/Z2l0aHViLmNvbS9oZWxpeGdpdHB4L2hlbGl4Z2l0cHgvZ2VuL2dvL2hlbGl4Z2l0cHgvb3JnL3YxO29yZ3YxogIDSE9YqgIRSGVsaXhnaXRweC5PcmcuVjHKAhFIZWxpeGdpdHB4XE9yZ1xWMeICHUhlbGl4Z2l0cHhcT3JnXFYxXEdQQk1ldGFkYXRh6gITSGVsaXhnaXRweDo6T3JnOjpWMWIGcHJvdG8z", [file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * @generated from message helixgitpx.org.v1.Org
 */
export type Org = Message<"helixgitpx.org.v1.Org"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string slug = 2;
   */
  slug: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message helixgitpx.org.v1.Org.
 * Use `create(OrgSchema)` to create a new message.
 */
export const OrgSchema: GenMessage<Org> = /*@__PURE__*/
  messageDesc(file_helixgitpx_org_v1_org, 0);

/**
 * @generated from message helixgitpx.org.v1.CreateOrgRequest
 */
export type CreateOrgRequest = Message<"helixgitpx.org.v1.CreateOrgRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message helixgitpx.org.v1.CreateOrgRequest.
 * Use `create(CreateOrgRequestSchema)` to create a new message.
 */
export const CreateOrgRequestSchema: GenMessage<CreateOrgRequest> = /*@__PURE__*/
  messageDesc(file_helixgitpx_org_v1_org, 1);

/**
 * @generated from message helixgitpx.org.v1.GetOrgRequest
 */
export type GetOrgRequest = Message<"helixgitpx.org.v1.GetOrgRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message helixgitpx.org.v1.GetOrgRequest.
 * Use `create(GetOrgRequestSchema)` to create a new message.
 */
export const GetOrgRequestSchema: GenMessage<GetOrgRequest> = /*@__PURE__*/
  messageDesc(file_helixgitpx_org_v1_org, 2);

/**
 * @generated from message helixgitpx.org.v1.UpdateOrgRequest
 */
export type UpdateOrgRequest = Message<"helixgitpx.org.v1.UpdateOrgRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message helixgitpx.org.v1.UpdateOrgRequest.
 * Use `create(UpdateOrgRequestSchema)` to create a new message.
 */
export const UpdateOrgRequestSchema: GenMessage<UpdateOrgRequest> = /*@__PURE__*/
  messageDesc(file_helixgitpx_org_v1_org, 3);

/**
 * @generated from message helixgitpx.org.v1.DeleteOrgRequest
 */
export type DeleteOrgRequest = Message<"helixgitpx.org.v1.DeleteOrgRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message helixgitpx.org.v1.DeleteOrgRequest.
 * Use `create(DeleteOrgRequestSchema)` to create a new message.
 */
export const DeleteOrgRequestSchema: GenMessage<DeleteOrgRequest> = /*@__PURE__*/
  messageDesc(file_helixgitpx_org_v1_org, 4);

/**
 * @generated from message helixgitpx.org.v1.ListOrgsRequest
 */
export type ListOrgsRequest = Message<"helixgitpx.org.v1.ListOrgsRequest"> & {
};

/**
 * Describes the message helixgitpx.org.v1.ListOrgsRequest.
 * Use `create(ListOrgsRequestSchema)` to create a new message.
 */
export const ListOrgsRequestSchema: GenMessage<ListOrgsRequest> = /*@__PURE__*/
  messageDesc(file_helixgitpx_org_v1_org, 5);

/**
 * @generated from message helixgitpx.org.v1.ListOrgsResponse
 */
export type ListOrgsResponse = Message<"helixgitpx.org.v1.ListOrgsResponse"> & {
  /**
   * @generated from field: repeated helixgitpx.org.v1.Org orgs = 1;
   */
  orgs: Org[];
};

/**
 * Describes the message helixgitpx.org.v1.ListOrgsResponse.
 * Use `create(ListOrgsResponseSchema)` to create a new message.
 */
export const ListOrgsResponseSchema: GenMessage<ListOrgsResponse> = /*@__PURE__*/
  messageDesc(file_helixgitpx_org_v1_org, 6);

/**
 * @generated from service helixgitpx.org.v1.OrgService
 */
export const OrgService: GenService<{
  /**
   * @generated from rpc helixgitpx.org.v1.OrgService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateOrgRequestSchema;
    output: typeof OrgSchema;
  },
  /**
   * @generated from rpc helixgitpx.org.v1.OrgService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetOrgRequestSchema;
    output: typeof OrgSchema;
  },
  /**
   * @generated from rpc helixgitpx.org.v1.OrgService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListOrgsRequestSchema;
    output: typeof ListOrgsResponseSchema;
  },
  /**
   * @generated from rpc helixgitpx.org.v1.OrgService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateOrgRequestSchema;
    output: typeof OrgSchema;
  },
  /**
   * @generated from rpc helixgitpx.org.v1.OrgService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteOrgRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_helixgitpx_org_v1_org, 0);

