// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/org/v1/org.proto (package helixgitpx.org.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateOrgRequest, DeleteOrgRequest, GetOrgRequest, ListOrgsRequest, ListOrgsResponse, Org, UpdateOrgRequest } from "./org_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helixgitpx.org.v1.OrgService
 */
export const OrgService = {
  typeName: "helixgitpx.org.v1.OrgService",
  methods: {
    /**
     * @generated from rpc helixgitpx.org.v1.OrgService.Create
     */
    create: {
      name: "Create",
      I: CreateOrgRequest,
      O: Org,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.org.v1.OrgService.Get
     */
    get: {
      name: "Get",
      I: GetOrgRequest,
      O: Org,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.org.v1.OrgService.List
     */
    list: {
      name: "List",
      I: ListOrgsRequest,
      O: ListOrgsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.org.v1.OrgService.Update
     */
    update: {
      name: "Update",
      I: UpdateOrgRequest,
      O: Org,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.org.v1.OrgService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteOrgRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

