// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/auth/v1/auth.proto (package helixgitpx.auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EnrollFIDO2Request, EnrollFIDO2Response, EnrollTOTPResponse, ExchangeOIDCRequest, IssuePATRequest, ListPATsResponse, ListSessionsResponse, MFAVerification, PAT, RefreshTokenRequest, RevokePATRequest, RevokeSessionRequest, Tokens, User, VerifyMFARequest } from "./auth_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helixgitpx.auth.v1.AuthService
 */
export const AuthService = {
  typeName: "helixgitpx.auth.v1.AuthService",
  methods: {
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.ExchangeOIDC
     */
    exchangeOIDC: {
      name: "ExchangeOIDC",
      I: ExchangeOIDCRequest,
      O: Tokens,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: RefreshTokenRequest,
      O: Tokens,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.IssuePAT
     */
    issuePAT: {
      name: "IssuePAT",
      I: IssuePATRequest,
      O: PAT,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.RevokePAT
     */
    revokePAT: {
      name: "RevokePAT",
      I: RevokePATRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.ListPATs
     */
    listPATs: {
      name: "ListPATs",
      I: Empty,
      O: ListPATsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.WhoAmI
     */
    whoAmI: {
      name: "WhoAmI",
      I: Empty,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.EnrollTOTP
     */
    enrollTOTP: {
      name: "EnrollTOTP",
      I: Empty,
      O: EnrollTOTPResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.EnrollFIDO2
     */
    enrollFIDO2: {
      name: "EnrollFIDO2",
      I: EnrollFIDO2Request,
      O: EnrollFIDO2Response,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.VerifyMFA
     */
    verifyMFA: {
      name: "VerifyMFA",
      I: VerifyMFARequest,
      O: MFAVerification,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.ListSessions
     */
    listSessions: {
      name: "ListSessions",
      I: Empty,
      O: ListSessionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.auth.v1.AuthService.RevokeSession
     */
    revokeSession: {
      name: "RevokeSession",
      I: RevokeSessionRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

