// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/auth/v1/auth.proto (package helixgitpx.auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message helixgitpx.auth.v1.ExchangeOIDCRequest
 */
export class ExchangeOIDCRequest extends Message<ExchangeOIDCRequest> {
  /**
   * @generated from field: string code = 1;
   */
  code = "";

  /**
   * @generated from field: string state = 2;
   */
  state = "";

  /**
   * @generated from field: string redirect_uri = 3;
   */
  redirectUri = "";

  constructor(data?: PartialMessage<ExchangeOIDCRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.ExchangeOIDCRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "redirect_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExchangeOIDCRequest {
    return new ExchangeOIDCRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExchangeOIDCRequest {
    return new ExchangeOIDCRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExchangeOIDCRequest {
    return new ExchangeOIDCRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ExchangeOIDCRequest | PlainMessage<ExchangeOIDCRequest> | undefined, b: ExchangeOIDCRequest | PlainMessage<ExchangeOIDCRequest> | undefined): boolean {
    return proto3.util.equals(ExchangeOIDCRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.RefreshTokenRequest
 */
export class RefreshTokenRequest extends Message<RefreshTokenRequest> {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken = "";

  constructor(data?: PartialMessage<RefreshTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.RefreshTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshTokenRequest {
    return new RefreshTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshTokenRequest {
    return new RefreshTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshTokenRequest {
    return new RefreshTokenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RefreshTokenRequest | PlainMessage<RefreshTokenRequest> | undefined, b: RefreshTokenRequest | PlainMessage<RefreshTokenRequest> | undefined): boolean {
    return proto3.util.equals(RefreshTokenRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.Tokens
 */
export class Tokens extends Message<Tokens> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken = "";

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken = "";

  /**
   * @generated from field: int64 expires_in = 3;
   */
  expiresIn = protoInt64.zero;

  constructor(data?: PartialMessage<Tokens>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.Tokens";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires_in", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tokens {
    return new Tokens().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tokens {
    return new Tokens().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tokens {
    return new Tokens().fromJsonString(jsonString, options);
  }

  static equals(a: Tokens | PlainMessage<Tokens> | undefined, b: Tokens | PlainMessage<Tokens> | undefined): boolean {
    return proto3.util.equals(Tokens, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.User
 */
export class User extends Message<User> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string subject = 2;
   */
  subject = "";

  /**
   * @generated from field: string email = 3;
   */
  email = "";

  /**
   * @generated from field: string display_name = 4;
   */
  displayName = "";

  /**
   * @generated from field: repeated string realm_roles = 5;
   */
  realmRoles: string[] = [];

  constructor(data?: PartialMessage<User>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.User";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "realm_roles", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User {
    return new User().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User {
    return new User().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User {
    return new User().fromJsonString(jsonString, options);
  }

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean {
    return proto3.util.equals(User, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.IssuePATRequest
 */
export class IssuePATRequest extends Message<IssuePATRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: repeated string scopes = 2;
   */
  scopes: string[] = [];

  /**
   * @generated from field: int64 expires_in_seconds = 3;
   */
  expiresInSeconds = protoInt64.zero;

  constructor(data?: PartialMessage<IssuePATRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.IssuePATRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "expires_in_seconds", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IssuePATRequest {
    return new IssuePATRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IssuePATRequest {
    return new IssuePATRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IssuePATRequest {
    return new IssuePATRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IssuePATRequest | PlainMessage<IssuePATRequest> | undefined, b: IssuePATRequest | PlainMessage<IssuePATRequest> | undefined): boolean {
    return proto3.util.equals(IssuePATRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.PAT
 */
export class PAT extends Message<PAT> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string token = 3;
   */
  token = "";

  /**
   * @generated from field: repeated string scopes = 4;
   */
  scopes: string[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 6;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<PAT>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.PAT";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "created_at", kind: "message", T: Timestamp },
    { no: 6, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PAT {
    return new PAT().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PAT {
    return new PAT().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PAT {
    return new PAT().fromJsonString(jsonString, options);
  }

  static equals(a: PAT | PlainMessage<PAT> | undefined, b: PAT | PlainMessage<PAT> | undefined): boolean {
    return proto3.util.equals(PAT, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.RevokePATRequest
 */
export class RevokePATRequest extends Message<RevokePATRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<RevokePATRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.RevokePATRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokePATRequest {
    return new RevokePATRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokePATRequest {
    return new RevokePATRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokePATRequest {
    return new RevokePATRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RevokePATRequest | PlainMessage<RevokePATRequest> | undefined, b: RevokePATRequest | PlainMessage<RevokePATRequest> | undefined): boolean {
    return proto3.util.equals(RevokePATRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.ListPATsResponse
 */
export class ListPATsResponse extends Message<ListPATsResponse> {
  /**
   * @generated from field: repeated helixgitpx.auth.v1.PAT pats = 1;
   */
  pats: PAT[] = [];

  constructor(data?: PartialMessage<ListPATsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.ListPATsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pats", kind: "message", T: PAT, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPATsResponse {
    return new ListPATsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPATsResponse {
    return new ListPATsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPATsResponse {
    return new ListPATsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListPATsResponse | PlainMessage<ListPATsResponse> | undefined, b: ListPATsResponse | PlainMessage<ListPATsResponse> | undefined): boolean {
    return proto3.util.equals(ListPATsResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.EnrollTOTPResponse
 */
export class EnrollTOTPResponse extends Message<EnrollTOTPResponse> {
  /**
   * @generated from field: string otpauth_url = 1;
   */
  otpauthUrl = "";

  /**
   * @generated from field: string secret = 2;
   */
  secret = "";

  constructor(data?: PartialMessage<EnrollTOTPResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.EnrollTOTPResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "otpauth_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "secret", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrollTOTPResponse {
    return new EnrollTOTPResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrollTOTPResponse {
    return new EnrollTOTPResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrollTOTPResponse {
    return new EnrollTOTPResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EnrollTOTPResponse | PlainMessage<EnrollTOTPResponse> | undefined, b: EnrollTOTPResponse | PlainMessage<EnrollTOTPResponse> | undefined): boolean {
    return proto3.util.equals(EnrollTOTPResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.EnrollFIDO2Request
 */
export class EnrollFIDO2Request extends Message<EnrollFIDO2Request> {
  /**
   * @generated from field: bytes attestation = 1;
   */
  attestation = new Uint8Array(0);

  constructor(data?: PartialMessage<EnrollFIDO2Request>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.EnrollFIDO2Request";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "attestation", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrollFIDO2Request {
    return new EnrollFIDO2Request().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrollFIDO2Request {
    return new EnrollFIDO2Request().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrollFIDO2Request {
    return new EnrollFIDO2Request().fromJsonString(jsonString, options);
  }

  static equals(a: EnrollFIDO2Request | PlainMessage<EnrollFIDO2Request> | undefined, b: EnrollFIDO2Request | PlainMessage<EnrollFIDO2Request> | undefined): boolean {
    return proto3.util.equals(EnrollFIDO2Request, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.EnrollFIDO2Response
 */
export class EnrollFIDO2Response extends Message<EnrollFIDO2Response> {
  /**
   * @generated from field: bytes public_key = 1;
   */
  publicKey = new Uint8Array(0);

  /**
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<EnrollFIDO2Response>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.EnrollFIDO2Response";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "public_key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrollFIDO2Response {
    return new EnrollFIDO2Response().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrollFIDO2Response {
    return new EnrollFIDO2Response().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrollFIDO2Response {
    return new EnrollFIDO2Response().fromJsonString(jsonString, options);
  }

  static equals(a: EnrollFIDO2Response | PlainMessage<EnrollFIDO2Response> | undefined, b: EnrollFIDO2Response | PlainMessage<EnrollFIDO2Response> | undefined): boolean {
    return proto3.util.equals(EnrollFIDO2Response, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.VerifyMFARequest
 */
export class VerifyMFARequest extends Message<VerifyMFARequest> {
  /**
   * @generated from field: string factor_id = 1;
   */
  factorId = "";

  /**
   * @generated from field: string totp_code = 2;
   */
  totpCode = "";

  /**
   * @generated from field: bytes fido2_assertion = 3;
   */
  fido2Assertion = new Uint8Array(0);

  constructor(data?: PartialMessage<VerifyMFARequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.VerifyMFARequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "factor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "totp_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "fido2_assertion", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VerifyMFARequest {
    return new VerifyMFARequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VerifyMFARequest {
    return new VerifyMFARequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VerifyMFARequest {
    return new VerifyMFARequest().fromJsonString(jsonString, options);
  }

  static equals(a: VerifyMFARequest | PlainMessage<VerifyMFARequest> | undefined, b: VerifyMFARequest | PlainMessage<VerifyMFARequest> | undefined): boolean {
    return proto3.util.equals(VerifyMFARequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.MFAVerification
 */
export class MFAVerification extends Message<MFAVerification> {
  /**
   * @generated from field: bool verified = 1;
   */
  verified = false;

  constructor(data?: PartialMessage<MFAVerification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.MFAVerification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MFAVerification {
    return new MFAVerification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MFAVerification {
    return new MFAVerification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MFAVerification {
    return new MFAVerification().fromJsonString(jsonString, options);
  }

  static equals(a: MFAVerification | PlainMessage<MFAVerification> | undefined, b: MFAVerification | PlainMessage<MFAVerification> | undefined): boolean {
    return proto3.util.equals(MFAVerification, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.Session
 */
export class Session extends Message<Session> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: string user_agent = 4;
   */
  userAgent = "";

  /**
   * @generated from field: string ip = 5;
   */
  ip = "";

  constructor(data?: PartialMessage<Session>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.Session";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "created_at", kind: "message", T: Timestamp },
    { no: 3, name: "expires_at", kind: "message", T: Timestamp },
    { no: 4, name: "user_agent", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "ip", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Session {
    return new Session().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Session {
    return new Session().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Session {
    return new Session().fromJsonString(jsonString, options);
  }

  static equals(a: Session | PlainMessage<Session> | undefined, b: Session | PlainMessage<Session> | undefined): boolean {
    return proto3.util.equals(Session, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.ListSessionsResponse
 */
export class ListSessionsResponse extends Message<ListSessionsResponse> {
  /**
   * @generated from field: repeated helixgitpx.auth.v1.Session sessions = 1;
   */
  sessions: Session[] = [];

  constructor(data?: PartialMessage<ListSessionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.ListSessionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sessions", kind: "message", T: Session, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSessionsResponse {
    return new ListSessionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSessionsResponse {
    return new ListSessionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSessionsResponse {
    return new ListSessionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListSessionsResponse | PlainMessage<ListSessionsResponse> | undefined, b: ListSessionsResponse | PlainMessage<ListSessionsResponse> | undefined): boolean {
    return proto3.util.equals(ListSessionsResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.auth.v1.RevokeSessionRequest
 */
export class RevokeSessionRequest extends Message<RevokeSessionRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<RevokeSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.auth.v1.RevokeSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeSessionRequest {
    return new RevokeSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeSessionRequest {
    return new RevokeSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeSessionRequest {
    return new RevokeSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeSessionRequest | PlainMessage<RevokeSessionRequest> | undefined, b: RevokeSessionRequest | PlainMessage<RevokeSessionRequest> | undefined): boolean {
    return proto3.util.equals(RevokeSessionRequest, a, b);
  }
}

