// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/policy/v1/policy.proto (package helixgitpx.policy.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message helixgitpx.policy.v1.Bundle
 */
export class Bundle extends Message<Bundle> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * semver
   *
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * @generated from field: string git_revision = 3;
   */
  gitRevision = "";

  /**
   * @generated from field: string etag = 4;
   */
  etag = "";

  /**
   * @generated from field: int64 size_bytes = 5;
   */
  sizeBytes = protoInt64.zero;

  /**
   * @generated from field: bytes sha256 = 6;
   */
  sha256 = new Uint8Array(0);

  /**
   * @generated from field: bool active = 7;
   */
  active = false;

  /**
   * @generated from field: bool signed = 8;
   */
  signed = false;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp activated_at = 10;
   */
  activatedAt?: Timestamp;

  constructor(data?: PartialMessage<Bundle>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.policy.v1.Bundle";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "git_revision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "etag", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "size_bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "sha256", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 7, name: "active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "signed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "created_at", kind: "message", T: Timestamp },
    { no: 10, name: "activated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Bundle {
    return new Bundle().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Bundle {
    return new Bundle().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Bundle {
    return new Bundle().fromJsonString(jsonString, options);
  }

  static equals(a: Bundle | PlainMessage<Bundle> | undefined, b: Bundle | PlainMessage<Bundle> | undefined): boolean {
    return proto3.util.equals(Bundle, a, b);
  }
}

/**
 * @generated from message helixgitpx.policy.v1.ListBundlesRequest
 */
export class ListBundlesRequest extends Message<ListBundlesRequest> {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit = 0;

  constructor(data?: PartialMessage<ListBundlesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.policy.v1.ListBundlesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBundlesRequest {
    return new ListBundlesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBundlesRequest {
    return new ListBundlesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBundlesRequest {
    return new ListBundlesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListBundlesRequest | PlainMessage<ListBundlesRequest> | undefined, b: ListBundlesRequest | PlainMessage<ListBundlesRequest> | undefined): boolean {
    return proto3.util.equals(ListBundlesRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.policy.v1.ListBundlesResponse
 */
export class ListBundlesResponse extends Message<ListBundlesResponse> {
  /**
   * @generated from field: repeated helixgitpx.policy.v1.Bundle bundles = 1;
   */
  bundles: Bundle[] = [];

  constructor(data?: PartialMessage<ListBundlesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.policy.v1.ListBundlesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bundles", kind: "message", T: Bundle, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBundlesResponse {
    return new ListBundlesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBundlesResponse {
    return new ListBundlesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBundlesResponse {
    return new ListBundlesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListBundlesResponse | PlainMessage<ListBundlesResponse> | undefined, b: ListBundlesResponse | PlainMessage<ListBundlesResponse> | undefined): boolean {
    return proto3.util.equals(ListBundlesResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.policy.v1.GetActiveRequest
 */
export class GetActiveRequest extends Message<GetActiveRequest> {
  constructor(data?: PartialMessage<GetActiveRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.policy.v1.GetActiveRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetActiveRequest {
    return new GetActiveRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetActiveRequest {
    return new GetActiveRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetActiveRequest {
    return new GetActiveRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetActiveRequest | PlainMessage<GetActiveRequest> | undefined, b: GetActiveRequest | PlainMessage<GetActiveRequest> | undefined): boolean {
    return proto3.util.equals(GetActiveRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.policy.v1.ActivateRequest
 */
export class ActivateRequest extends Message<ActivateRequest> {
  /**
   * @generated from field: string bundle_id = 1;
   */
  bundleId = "";

  /**
   * @generated from field: string actor_id = 2;
   */
  actorId = "";

  /**
   * @generated from field: string reason = 3;
   */
  reason = "";

  constructor(data?: PartialMessage<ActivateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.policy.v1.ActivateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bundle_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ActivateRequest {
    return new ActivateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ActivateRequest {
    return new ActivateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ActivateRequest {
    return new ActivateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ActivateRequest | PlainMessage<ActivateRequest> | undefined, b: ActivateRequest | PlainMessage<ActivateRequest> | undefined): boolean {
    return proto3.util.equals(ActivateRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.policy.v1.RollbackRequest
 */
export class RollbackRequest extends Message<RollbackRequest> {
  /**
   * @generated from field: string target_bundle_id = 1;
   */
  targetBundleId = "";

  /**
   * @generated from field: string actor_id = 2;
   */
  actorId = "";

  /**
   * @generated from field: string reason = 3;
   */
  reason = "";

  constructor(data?: PartialMessage<RollbackRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.policy.v1.RollbackRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_bundle_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollbackRequest {
    return new RollbackRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollbackRequest {
    return new RollbackRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollbackRequest {
    return new RollbackRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RollbackRequest | PlainMessage<RollbackRequest> | undefined, b: RollbackRequest | PlainMessage<RollbackRequest> | undefined): boolean {
    return proto3.util.equals(RollbackRequest, a, b);
  }
}

