// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/policy/v1/policy.proto (package helixgitpx.policy.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivateRequest, Bundle, GetActiveRequest, ListBundlesRequest, ListBundlesResponse, RollbackRequest } from "./policy_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * PolicyBundleService is the opa-bundle-server's RPC surface. HTTP is the
 * primary path (OPA agents pull via the `httpbundle` plugin); RPC is for
 * admin ops (list, activate, rollback).
 *
 * @generated from service helixgitpx.policy.v1.PolicyBundleService
 */
export const PolicyBundleService = {
  typeName: "helixgitpx.policy.v1.PolicyBundleService",
  methods: {
    /**
     * @generated from rpc helixgitpx.policy.v1.PolicyBundleService.ListBundles
     */
    listBundles: {
      name: "ListBundles",
      I: ListBundlesRequest,
      O: ListBundlesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.policy.v1.PolicyBundleService.GetActive
     */
    getActive: {
      name: "GetActive",
      I: GetActiveRequest,
      O: Bundle,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.policy.v1.PolicyBundleService.Activate
     */
    activate: {
      name: "Activate",
      I: ActivateRequest,
      O: Bundle,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.policy.v1.PolicyBundleService.Rollback
     */
    rollback: {
      name: "Rollback",
      I: RollbackRequest,
      O: Bundle,
      kind: MethodKind.Unary,
    },
  }
} as const;

