// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file helixgitpx/repo/v1/repo.proto (package helixgitpx.repo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message helixgitpx.repo.v1.Repo
 */
export class Repo extends Message<Repo> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string org_id = 2;
   */
  orgId = "";

  /**
   * @generated from field: string slug = 3;
   */
  slug = "";

  /**
   * @generated from field: string default_branch = 4;
   */
  defaultBranch = "";

  /**
   * @generated from field: bool lfs_enabled = 5;
   */
  lfsEnabled = false;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Repo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.Repo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "default_branch", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "lfs_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Repo {
    return new Repo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Repo {
    return new Repo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Repo {
    return new Repo().fromJsonString(jsonString, options);
  }

  static equals(a: Repo | PlainMessage<Repo> | undefined, b: Repo | PlainMessage<Repo> | undefined): boolean {
    return proto3.util.equals(Repo, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.BranchProtection
 */
export class BranchProtection extends Message<BranchProtection> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: string pattern = 2;
   */
  pattern = "";

  /**
   * @generated from field: bool require_signed = 3;
   */
  requireSigned = false;

  /**
   * @generated from field: int32 required_reviewers = 4;
   */
  requiredReviewers = 0;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<BranchProtection>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.BranchProtection";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "require_signed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "required_reviewers", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BranchProtection {
    return new BranchProtection().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BranchProtection {
    return new BranchProtection().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BranchProtection {
    return new BranchProtection().fromJsonString(jsonString, options);
  }

  static equals(a: BranchProtection | PlainMessage<BranchProtection> | undefined, b: BranchProtection | PlainMessage<BranchProtection> | undefined): boolean {
    return proto3.util.equals(BranchProtection, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.Ref
 */
export class Ref extends Message<Ref> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string sha = 2;
   */
  sha = "";

  constructor(data?: PartialMessage<Ref>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.Ref";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sha", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Ref {
    return new Ref().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Ref {
    return new Ref().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Ref {
    return new Ref().fromJsonString(jsonString, options);
  }

  static equals(a: Ref | PlainMessage<Ref> | undefined, b: Ref | PlainMessage<Ref> | undefined): boolean {
    return proto3.util.equals(Ref, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.CreateRepoRequest
 */
export class CreateRepoRequest extends Message<CreateRepoRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  /**
   * @generated from field: string slug = 2;
   */
  slug = "";

  /**
   * @generated from field: string default_branch = 3;
   */
  defaultBranch = "";

  /**
   * @generated from field: bool lfs_enabled = 4;
   */
  lfsEnabled = false;

  constructor(data?: PartialMessage<CreateRepoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.CreateRepoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "default_branch", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "lfs_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRepoRequest {
    return new CreateRepoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRepoRequest {
    return new CreateRepoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRepoRequest {
    return new CreateRepoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRepoRequest | PlainMessage<CreateRepoRequest> | undefined, b: CreateRepoRequest | PlainMessage<CreateRepoRequest> | undefined): boolean {
    return proto3.util.equals(CreateRepoRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.GetRepoRequest
 */
export class GetRepoRequest extends Message<GetRepoRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  /**
   * @generated from field: string slug = 2;
   */
  slug = "";

  constructor(data?: PartialMessage<GetRepoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.GetRepoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRepoRequest {
    return new GetRepoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRepoRequest {
    return new GetRepoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRepoRequest {
    return new GetRepoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRepoRequest | PlainMessage<GetRepoRequest> | undefined, b: GetRepoRequest | PlainMessage<GetRepoRequest> | undefined): boolean {
    return proto3.util.equals(GetRepoRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.UpdateRepoRequest
 */
export class UpdateRepoRequest extends Message<UpdateRepoRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  /**
   * @generated from field: string slug = 2;
   */
  slug = "";

  /**
   * @generated from field: string default_branch = 3;
   */
  defaultBranch = "";

  /**
   * @generated from field: bool lfs_enabled = 4;
   */
  lfsEnabled = false;

  constructor(data?: PartialMessage<UpdateRepoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.UpdateRepoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "default_branch", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "lfs_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRepoRequest {
    return new UpdateRepoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRepoRequest {
    return new UpdateRepoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRepoRequest {
    return new UpdateRepoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRepoRequest | PlainMessage<UpdateRepoRequest> | undefined, b: UpdateRepoRequest | PlainMessage<UpdateRepoRequest> | undefined): boolean {
    return proto3.util.equals(UpdateRepoRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.DeleteRepoRequest
 */
export class DeleteRepoRequest extends Message<DeleteRepoRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  /**
   * @generated from field: string slug = 2;
   */
  slug = "";

  constructor(data?: PartialMessage<DeleteRepoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.DeleteRepoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteRepoRequest {
    return new DeleteRepoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteRepoRequest {
    return new DeleteRepoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteRepoRequest {
    return new DeleteRepoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteRepoRequest | PlainMessage<DeleteRepoRequest> | undefined, b: DeleteRepoRequest | PlainMessage<DeleteRepoRequest> | undefined): boolean {
    return proto3.util.equals(DeleteRepoRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.ListReposRequest
 */
export class ListReposRequest extends Message<ListReposRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId = "";

  constructor(data?: PartialMessage<ListReposRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.ListReposRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListReposRequest {
    return new ListReposRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListReposRequest {
    return new ListReposRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListReposRequest {
    return new ListReposRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListReposRequest | PlainMessage<ListReposRequest> | undefined, b: ListReposRequest | PlainMessage<ListReposRequest> | undefined): boolean {
    return proto3.util.equals(ListReposRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.ListReposResponse
 */
export class ListReposResponse extends Message<ListReposResponse> {
  /**
   * @generated from field: repeated helixgitpx.repo.v1.Repo repos = 1;
   */
  repos: Repo[] = [];

  constructor(data?: PartialMessage<ListReposResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.ListReposResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repos", kind: "message", T: Repo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListReposResponse {
    return new ListReposResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListReposResponse {
    return new ListReposResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListReposResponse {
    return new ListReposResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListReposResponse | PlainMessage<ListReposResponse> | undefined, b: ListReposResponse | PlainMessage<ListReposResponse> | undefined): boolean {
    return proto3.util.equals(ListReposResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.ListRefsRequest
 */
export class ListRefsRequest extends Message<ListRefsRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  constructor(data?: PartialMessage<ListRefsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.ListRefsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRefsRequest {
    return new ListRefsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRefsRequest {
    return new ListRefsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRefsRequest {
    return new ListRefsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRefsRequest | PlainMessage<ListRefsRequest> | undefined, b: ListRefsRequest | PlainMessage<ListRefsRequest> | undefined): boolean {
    return proto3.util.equals(ListRefsRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.ListRefsResponse
 */
export class ListRefsResponse extends Message<ListRefsResponse> {
  /**
   * @generated from field: repeated helixgitpx.repo.v1.Ref refs = 1;
   */
  refs: Ref[] = [];

  constructor(data?: PartialMessage<ListRefsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.ListRefsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "refs", kind: "message", T: Ref, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRefsResponse {
    return new ListRefsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRefsResponse {
    return new ListRefsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRefsResponse {
    return new ListRefsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListRefsResponse | PlainMessage<ListRefsResponse> | undefined, b: ListRefsResponse | PlainMessage<ListRefsResponse> | undefined): boolean {
    return proto3.util.equals(ListRefsResponse, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.ProtectRefRequest
 */
export class ProtectRefRequest extends Message<ProtectRefRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: string pattern = 2;
   */
  pattern = "";

  /**
   * @generated from field: bool require_signed = 3;
   */
  requireSigned = false;

  /**
   * @generated from field: int32 required_reviewers = 4;
   */
  requiredReviewers = 0;

  constructor(data?: PartialMessage<ProtectRefRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.ProtectRefRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "require_signed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "required_reviewers", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProtectRefRequest {
    return new ProtectRefRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProtectRefRequest {
    return new ProtectRefRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProtectRefRequest {
    return new ProtectRefRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ProtectRefRequest | PlainMessage<ProtectRefRequest> | undefined, b: ProtectRefRequest | PlainMessage<ProtectRefRequest> | undefined): boolean {
    return proto3.util.equals(ProtectRefRequest, a, b);
  }
}

/**
 * @generated from message helixgitpx.repo.v1.UnprotectRefRequest
 */
export class UnprotectRefRequest extends Message<UnprotectRefRequest> {
  /**
   * @generated from field: string repo_id = 1;
   */
  repoId = "";

  /**
   * @generated from field: string pattern = 2;
   */
  pattern = "";

  constructor(data?: PartialMessage<UnprotectRefRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "helixgitpx.repo.v1.UnprotectRefRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnprotectRefRequest {
    return new UnprotectRefRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnprotectRefRequest {
    return new UnprotectRefRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnprotectRefRequest {
    return new UnprotectRefRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnprotectRefRequest | PlainMessage<UnprotectRefRequest> | undefined, b: UnprotectRefRequest | PlainMessage<UnprotectRefRequest> | undefined): boolean {
    return proto3.util.equals(UnprotectRefRequest, a, b);
  }
}

