// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file helixgitpx/repo/v1/repo.proto (package helixgitpx.repo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BranchProtection, CreateRepoRequest, DeleteRepoRequest, GetRepoRequest, ListRefsRequest, ListRefsResponse, ListReposRequest, ListReposResponse, ProtectRefRequest, Repo, UnprotectRefRequest, UpdateRepoRequest } from "./repo_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helixgitpx.repo.v1.RepoService
 */
export const RepoService = {
  typeName: "helixgitpx.repo.v1.RepoService",
  methods: {
    /**
     * @generated from rpc helixgitpx.repo.v1.RepoService.Create
     */
    create: {
      name: "Create",
      I: CreateRepoRequest,
      O: Repo,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.repo.v1.RepoService.Get
     */
    get: {
      name: "Get",
      I: GetRepoRequest,
      O: Repo,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.repo.v1.RepoService.List
     */
    list: {
      name: "List",
      I: ListReposRequest,
      O: ListReposResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.repo.v1.RepoService.Update
     */
    update: {
      name: "Update",
      I: UpdateRepoRequest,
      O: Repo,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.repo.v1.RepoService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteRepoRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service helixgitpx.repo.v1.RefService
 */
export const RefService = {
  typeName: "helixgitpx.repo.v1.RefService",
  methods: {
    /**
     * @generated from rpc helixgitpx.repo.v1.RefService.List
     */
    list: {
      name: "List",
      I: ListRefsRequest,
      O: ListRefsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.repo.v1.RefService.Protect
     */
    protect: {
      name: "Protect",
      I: ProtectRefRequest,
      O: BranchProtection,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc helixgitpx.repo.v1.RefService.Unprotect
     */
    unprotect: {
      name: "Unprotect",
      I: UnprotectRefRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

