// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file helixgitpx/repo/v1/stubs.proto (package helixgitpx.repo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helixgitpx/repo/v1/stubs.proto.
 */
export const file_helixgitpx_repo_v1_stubs: GenFile = /*@__PURE__*/
  fileDesc("Ch5oZWxpeGdpdHB4L3JlcG8vdjEvc3R1YnMucHJvdG8SEmhlbGl4Z2l0cHgucmVwby52MSIfCgtQbGFjZWhvbGRlchIQCghyZXNlcnZlZBgBIAEoCULRAQoWY29tLmhlbGl4Z2l0cHgucmVwby52MUIKU3R1YnNQcm90b1ABWkFnaXRodWIuY29tL2hlbGl4Z2l0cHgvaGVsaXhnaXRweC9nZW4vZ28vaGVsaXhnaXRweC9yZXBvL3YxO3JlcG92MaICA0hSWKoCEkhlbGl4Z2l0cHguUmVwby5WMcoCEkhlbGl4Z2l0cHhcUmVwb1xWMeICHkhlbGl4Z2l0cHhcUmVwb1xWMVxHUEJNZXRhZGF0YeoCFEhlbGl4Z2l0cHg6OlJlcG86OlYxYgZwcm90bzM");

/**
 * Stub placeholder — real messages and services land in the milestone owning this domain.
 * See proto/README.md for the M1 → Mx ownership table.
 *
 * @generated from message helixgitpx.repo.v1.Placeholder
 */
export type Placeholder = Message<"helixgitpx.repo.v1.Placeholder"> & {
  /**
   * @generated from field: string reserved = 1;
   */
  reserved: string;
};

/**
 * Describes the message helixgitpx.repo.v1.Placeholder.
 * Use `create(PlaceholderSchema)` to create a new message.
 */
export const PlaceholderSchema: GenMessage<Placeholder> = /*@__PURE__*/
  messageDesc(file_helixgitpx_repo_v1_stubs, 0);

